"""
Ukrainian language dictionary for Secure Pass Pro v4.0
Украинский словарь для Secure Pass Pro v4.0
Український словник для Secure Pass Pro v4.0

FIXED: Added full type hints for dictionary
"""
from __future__ import annotations

from typing import Dict, List, Any, Optional

# ==================== UKRAINIAN DICTIONARY ====================

UKRAINIAN_DICT: Dict[str, str] = {
    # Main window
    "win_title": "🔐 Secure Pass Pro v4.0",
    "menu_title": "📋 Меню",
    "len": "📏 Довжина",
    "author": "👤 Автор: Максим Мельніков",
    "upper": "🔠 Великі літери",
    "lower": "🔡 Малі літери",
    "digits": "🔢 Цифри",
    "symb": "✨ Спецсимволи",
    "ambig": "🚫 Виключити схожі",
    "unambig": "🚫 Виключити неоднозначні",
    "at_least": "✅ Мінімум 1 з кожної категорії",
    "hide": "👁 Приховувати символи",
    "no_repeat": "🔄 Уникати повторів символів поспіль",
    "warn": "⚠️ Увага",
    "no_pwd": "⚠️ Немає пароля для збереження!",
    
    # Menu buttons
    "btn_gen": "🎲 Згенерувати",
    "btn_name_gen": "👤 Генератор імен",
    "btn_passphrase": "🔐 Парольна фраза",
    "btn_copy": "📋 Копіювати пароль",
    "btn_save": "💾 Зберегти у файл",
    "btn_open": "📂 Відкрити файл",
    "btn_qr": "📱 QR-код",
    "btn_hist": "📜 Історія",
    "btn_db": "🗄 База паролів",
    "btn_hibp": "🔍 Перевірити витоки",
    "btn_upd": "🔄 Оновити",
    "btn_settings": "⚙️ Налаштування",
    "btn_about": "ℹ️ Про програму",
    "btn_clear_hist": "🗑️ Очистити історію",
    "btn_eye": "👁",
    "btn_eye_closed": "🙈",
    
    # Tooltips
    "tt_gen": "🎲 Створити новий випадковий пароль (F5)",
    "tt_name_gen": "👤 Генерація імен для будь-яких цілей",
    "tt_passphrase": "🔐 Генерація парольної фрази (Diceware)\nКожне слово додає ~13 біт ентропії",
    "tt_copy": "📋 Копіювати в буфер (очищення через {0} сек)",
    "tt_save": "💾 Зберегти поточний пароль у файл (Ctrl+S)",
    "tt_open": "📂 Відкрити пароль з файлу (Ctrl+O)",
    "tt_qr": "📱 Створити QR-код для швидкого сканування",
    "tt_hist": "📜 Показати останні 50 паролів",
    "tt_db": "🗄️ Відкрити сховище паролів",
    "tt_hibp": "🔍 Перевірити пароль у базі витоків",
    "tt_upd": "🔄 Перевірити наявність нової версії",
    "tt_about": "ℹ️ Інформація про програму",
    "tt_settings": "⚙️ Налаштування програми",
    "tt_eye": "👁 Показати / приховати пароль",
    "tt_no_repeat": "🔄 Не допускати однакових символів підряд",
    "tt_auto_lock": "🔒 Автоматичне блокування при бездіяльності",
    "tt_clip_timeout": "⏱️ Через скільки секунд буфер обміну буде очищено",
    
    # Name generator
    "name_gen_title": "👤 Генератор імен",
    "name_gen_type_label": "📋 Тип генерації",
    "name_gen_samp": "🎮 SAMP RP",
    "name_gen_email": "📧 Email адреса",
    "name_gen_game": "🎮 Ігровий нік",
    "name_gen_cool": "😎 Крутий нік",
    "name_gen_beauty": "✨ Красивий нік",
    "name_gen_short": "📏 Короткий (3-5)",
    "name_gen_long": "📏 Довгий (8+)",
    "name_gen_random": "🎲 Випадковий",
    "name_gen_settings_label": "⚙️ Налаштування",
    "name_gen_gender": "👤 Стать:",
    "name_gen_male": "👨 Чоловіча",
    "name_gen_female": "👩 Жіноча",
    "name_gen_random_gender": "🎲 Випадкова",
    "name_gen_lang": "🌐 Мова:",
    "name_gen_russian": "🇷🇺 Російська",
    "name_gen_english": "🇬🇧 English",
    "name_gen_separator": "🔗 Розділювач:",
    "name_gen_separator_yes": "✅ ТАК (_)",
    "name_gen_separator_no": "❌ НІ",
    "name_gen_count": "🔢 Кількість:",
    "name_gen_generate_btn": "🎲 Згенерувати",
    "name_gen_clear_btn": "🗑️ Очистити",
    "name_gen_copy_btn": "📋 Копіювати всі",
    "name_gen_result_label": "📝 Результат",
    "name_gen_copied": "✅ Скопійовано {0} імен!",
    "name_gen_generating": "⏳ Генерація...",
    "name_gen_error": "❌ Помилка генерації імен",
    
    # Password strength
    "strength": "🔒 Стійкість: ~{0} варіантів",
    "crack_time": "⏱️ {0}",
    "time_sec": "⚡ секунди на злам",
    "time_day": "📅 дні на злам",
    "time_year": "📆 роки на злам",
    "time_cent": "🏛️ століття на злам",
    "st_low": "🔴 Слабкий пароль",
    "st_mid": "🟡 Середній пароль",
    "st_high": "🟢 Надійний пароль",
    "strength_weak": "Слабкий",
    "strength_medium": "Середній",
    "strength_medium_plus": "Середній+",
    "strength_strong": "Надійний",
    
    # Settings window
    "settings_search": "🔍 Пошук налаштувань...",
    "settings_title": "⚙️ Налаштування",
    "settings_subtitle": "⚙️ Налаштуйте додаток під свої потреби",
    "settings_lang": "🌐 Мова інтерфейсу",
    "settings_lang_desc": "🌐 Виберіть мову інтерфейсу",
    "settings_sound": "🔊 Звук програми",
    "settings_theme": "🎨 Тема оформлення",
    "settings_theme_desc": "🎨 Виберіть оформлення додатку",
    "settings_radius": "🔘 Закруглення кутів",
    "radius_desc": "🔘 Закруглення кутів елементів",
    "font_size": "🔤 Розмір шрифту",
    "font_size_desc": "🔤 Розмір тексту в інтерфейсі",
    "theme_sys": "💻 Системна",
    "theme_dark": "🌙 Темна",
    "theme_light": "☀️ Світла",
    "sound_on": "🔊 Звук: увімк",
    "sound_off": "🔇 Звук: вимк",
    "sound_desc": "🔊 Звукові ефекти при діях",
    "close": "❌ Закрити",
    "ok": "✅ Гаразд",
    "cancel": "❌ Скасувати",
    "yes": "✅ Так",
    "no": "❌ Ні",
    "save": "💾 Зберегти",
    "delete": "🗑️ Видалити",
    "edit": "✏️ Редагувати",
    "copy": "📋 Копіювати",
    "clear": "🗑️ Очистити",
    "back": "🔙 Назад",
    "next": "➡️ Далі",
    "finish": "✅ Завершити",
    "apply": "✅ Застосувати",
    "reset": "🔄 Скинути",
    "refresh": "🔄 Оновити",
    "tab_design": "🎨 Дизайн",
    "tab_security": "🔒 Безпека",
    "tab_general": "⚙️ Загальні",
    "tab_cloud": "☁ Хмара",
    
    # RGB Settings
    "rgb_label": "🌈 RGB-підсвітка",
    "rgb_label_desc": "🌈 Кольорова анімація границь",
    "rgb_on": "✅ Увімк",
    "rgb_off": "❌ Вимк",
    "rgb_speed": "⚡ Швидкість RGB",
    "rgb_speed_desc": "⚡ Швидкість анімації",
    "rgb_speed_slow": "🐢 Повільна",
    "rgb_speed_normal": "⚡ Нормальна",
    "rgb_speed_fast": "🚀 Швидка",
    "rgb_width": "📏 Товщина RGB",
    "rgb_width_desc": "📏 Товщина підсвітки",
    "rgb_width_thin": "➖ Тонка",
    "rgb_width_normal": "➖➖ Середня",
    "rgb_width_thick": "🔲 Товста",
    
    # Auto save
    "auto_save": "💾 Автозбереження",
    "auto_save_desc": "💾 Автоматичне збереження паролів",
    "auto_save_on": "✅ Увімкнено",
    "auto_save_off": "❌ Вимкнено",
    "auto_save_enabled": "✅ Автозбереження увімкнено",
    "auto_save_disabled": "❌ Автозбереження вимкнено",
    "auto_save_label": "💾 Автозбереження",
    
    # Auto lock
    "auto_lock": "🔒 Автоблокування",
    "auto_lock_desc": "🔒 Автоматичне блокування при бездіяльності",
    "auto_lock_timeout": "⏰ Таймаут блокування: {0} хв",
    "auto_lock_title": "🔒 Програму заблоковано",
    "unlock": "🔓 Розблокувати",
    
    # Clipboard
    "clip_timeout": "📋 Очищення буфера: {0} сек",
    "clip_timeout_desc": "📋 Автоочищення буфера обміну",
    "clipboard_cleared": "✅ Буфер обміну очищено",
    "clipboard_auto_clear": "📋 Автоочищення буфера через {0} сек",
    "clear_clipboard": "🗑️ Очистити буфер обміну",
    "pwd_done": "✅ Пароль скопійовано",
    "copied": "✅ Скопійовано! ({0}с)",
    
    # Master password
    "master_title": "🔐 Майстер-пароль",
    "master_desc": "🔐 Захист доступу до програми",
    "master_prompt": "🔑 Введіть майстер-пароль:",
    "master_set_title": "🔐 Встановити майстер-пароль",
    "master_set_prompt": "🔑 Придумайте майстер-пароль:",
    "master_confirm": "✅ Підтвердіть майстер-пароль:",
    "master_mismatch": "❌ Паролі не збігаються",
    "master_wrong": "❌ Невірний пароль! Спроба {0} з {1}",
    "master_blocked": "🚫 Перевищено кількість спроб. Програму закрито",
    "master_set_ok": "✅ Майстер-пароль встановлено",
    "master_removed": "✅ Майстер-пароль видалено",
    "master_btn_set": "🔐 Встановити майстер-пароль",
    "master_btn_remove": "🗑️ Видалити майстер-пароль",
    "master_current": "📊 Статус:",
    "master_status_set": "✅ Встановлено",
    "master_status_not_set": "❌ Не встановлено",
    "master_remove_confirm": "⚠️ Видалити майстер-пароль?",
    "master_remove_prompt": "🔑 Введіть поточний майстер-пароль:",
    "master_not_set": "❌ Майстер-пароль не встановлено",
    "master_already_set": "✅ Майстер-пароль вже встановлено",
    "master_set_error": "❌ Помилка встановлення майстер-пароля",
    "master_remove_error": "❌ Помилка видалення майстер-пароля",
    "master_status_text": "🔐 Майстер-пароль: встановлено",
    "master_status_not_set_text": "⚠️ Майстер-пароль: не встановлено",
    "master_too_short": "⚠️ Пароль занадто короткий. Мінімум 8 символів",
    "master_weak": "⚠️ Пароль занадто простий. Додайте цифру або спецсимвол",
    "master_verified": "✅ Майстер-пароль підтверджено",
    
    # Database window
    "db_title": "🗄️ База паролів",
    "db_search": "🔍 Пошук",
    "db_search_placeholder": "🔍 Пошук за міткою, паролем, URL, логіном, email...",
    "db_save_current": "💾 Зберегти поточний пароль",
    "db_save_current_btn": "💾 Зберегти поточний пароль",
    "db_saved": "✅ Пароль збережено!",
    "db_save_success": "✅ Пароль збережено!",
    "db_no_pass": "❌ Спочатку згенеруйте пароль!",
    "db_count": "📊 Записів: {0}",
    "db_empty": "📭 База порожня",
    "db_no_label": "🏷️ Без мітки",
    "db_edit_title": "✏️ Редагувати запис",
    "db_edit_label": "📝 Мітка",
    "db_edit_pass": "🔑 Пароль",
    "db_edit_url": "🔗 URL / Сайт",
    "db_edit_username": "👤 Логін",
    "db_edit_email": "📧 Email",
    "db_edit_category": "📁 Категорія",
    "db_edit_favorite": "⭐ Обране",
    "db_category_filter": "📁 Категорія",
    "db_favorites_only": "⭐ Тільки обрані",
    "db_copy": "Копіювати",
    "db_edit": "Редагувати",
    "db_delete": "Видалити",
    "db_del_confirm": "🗑️ Видалити цей запис?",
    "db_delete_success": "✅ Запис видалено!",
    "db_import": "📂 Імпорт паролів",
    "db_label_prompt": "🏷️ Мітка:",
    "db_save_error": "❌ Помилка збереження",
    "db_delete_error": "❌ Помилка видалення",
    "db_search_no_results": "🔍 Нічого не знайдено",
    "db_notes": "📝 Нотатки",
    
    # History
    "hist_empty": "📭 Історія порожня",
    
    # PDF
    "pdf_date": "Дата",
    "pdf_pass": "Пароль",
    "pdf_theme": "📄 Тема PDF",
    "pdf_theme_desc": "📄 Оформлення експорту в PDF",
    "pdf_theme_light": "☀️ Світла",
    "pdf_theme_dark": "🌙 Темна",
    
    # QR
    "qr_closes_in": "⏰ Вікно закриється через",
    "seconds_short": "сек",
    
    # Lock screen
    "lock_screen_title": "🔒 Введіть майстер-пароль",
    "lock_wait": "⏳ Зачекайте",
    
    # HIBP
    "hibp_no_password": "⚠️ Спочатку згенеруйте пароль",
    "hibp_checking": "🔍 Перевірка...",
    "hibp_safe": "✅ Пароль безпечний",
    "hibp_found": "❌ Пароль знайдено в {count} витоках",
    "hibp_error": "⚠️ Помилка перевірки",
    "hibp_error_title": "❌ Помилка перевірки",
    "hibp_safe_title": "✅ Пароль безпечний",
    "hibp_found_title": "🚨 УВАГА! Пароль скомпрометовано",
    "hibp_warning": "⚠️ Рекомендується змінити пароль",
    "hibp_rate_limit": "⏳ Будь ласка, зачекайте {0} секунд перед наступною перевіркою.\nЦе захищає сервер від перевантаження.",
    "hibp_check_error": "❌ Не вдалося підключитися до сервера.\nБудь ласка, перевірте інтернет-з'єднання.",
    "hibp_safe_message": "🔒 Пароль не знайдено в базах витоків.\n\nБезпечно використовувати.",
    "hibp_found_message": "⚠️ Пароль знайдено {0} раз(и) у витоках!\n\nЗгенеруйте новий пароль.",
    "hibp_change_password": "🔑 Рекомендується негайно змінити пароль!",
    "hibp_generate_new": "🔄 Згенерувати новий пароль",
    "hibp_close": "❌ Закрити",
    "hibp_checking_title": "🔍 Перевірка пароля...",
    "hibp_result_title": "🔍 Результат перевірки витоків",
    "hibp_check_button": "🔍 Перевірити витоки",
    "hibp_checking_status": "🔍 Перевірка...",
    
    # Update
    "update_check": "🔄 Перевірка оновлень",
    "update_available": "📦 Доступна версія {0}",
    "update_not_available": "✅ Встановлено останню версію",
    "update_available_title": "📦 Доступно оновлення",
    "update_confirm_title": "🔄 Оновлення",
    "update_confirm_message": "📥 Встановити оновлення?",
    "update_error": "❌ Помилка оновлення",
    "update_signature_error": "❌ Перевірка підпису оновлення не вдалася!",
    "update_integrity_error": "❌ Перевірка цілісності оновлення не вдалася!",
    "update_restart": "✅ Оновлення успішно завантажено!\n\n🔄 Додаток перезапуститься для застосування змін.",
    "download_start": "📥 Завантаження оновлення...",
    "update_installing": "⚙️ Встановлення оновлення...",
    "update_rollback": "⏪ Виконано відкат",
    "update_rollback_message": "⚠️ Встановлення не вдалося, виконано відкат до попередньої версії.",
    "update_cancelled": "❌ Оновлення скасовано",
    "update_no_backup": "📭 Немає збережених резервних копій для відкату.",
    "update_rollback_confirm": "⚠️ Ви впевнені, що хочете відкотитися до попередньої версії?\n\nБудь-які незбережені зміни будуть втрачені.",
    "update_rollback_success": "✅ Відкат виконано успішно.\n\n🔄 Додаток буде перезапущено.",
    "update_rollback_error": "❌ Не вдалося виконати відкат.",
    "update_info": "ℹ️ Поточна версія: {0}",
    "update_date": "📅 Дата",
    "update_size": "📦 Розмір",
    
    # Security
    "security": "🔒 Безпека",
    "security_audit_pass": "✅ Перевірку безпеки пройдено",
    "security_audit_fail": "⚠️ Виявлено проблеми безпеки",
    "wiki_link": "📖 Wiki / Вікі",
    "rate_limit_warning": "⚠️ Режим 'без повторів' знижує стійкість",
    "duplicate_warning": "⚠️ Такий пароль вже існує в базі.\n\n💾 Зберегти все одно?",
    "skip_duplicates": "⏭️ Пропускати дублікати паролів",
    "continue_anyway": "⚠️ Все одно продовжити?",
    "truncate_question": "✂️ Обрізати до {0} символів?",
    
    # SQLCipher
    "sqlcipher_enabled": "✅ SQLCipher увімкнено",
    "sqlcipher_disabled": "❌ SQLCipher вимкнено",
    
    # Errors
    "err_cat": "⚠️ Виберіть хоча б одну категорію",
    "err_pool_small": "⚠️ Занадто мало доступних символів",
    "err_save": "❌ Помилка збереження: {0}",
    "err_open": "❌ Не вдалося прочитати файл: {0}",
    "err_unsupported": "❌ Непідтримуваний тип файлу: {0}",
    "err_integrity": "🚨 Критична помилка: Файл пошкоджено",
    "err_no_repeat": "⚠️ Не вдалося створити пароль без повторів",
    "err_no_repeat_fallback": "\n⚠️ Використано пароль з повторами",
    "err_title": "❌ Помилка",
    "err_encrypt": "🔒 Помилка шифрування",
    "err_decrypt": "🔓 Помилка дешифрування",
    "err_database": "🗄️ Помилка бази даних",
    "err_network": "🌐 Помилка мережі",
    "err_permission": "🔐 Помилка доступу",
    "err_copy": "📋 Помилка копіювання",
    "err_qr": "📱 Помилка створення QR-коду",
    "err_timeout": "⏰ Перевищено час очікування",
    "err_import": "❌ Помилка імпорту модуля",
    "err_file_too_large": "📁 Файл занадто великий",
    "err_invalid_format": "📄 Невірний формат файлу",
    "err_malformed": "💥 Файл пошкоджено",
    "err_encoding": "🔤 Непідтримуване кодування файлу",
    "err_file_empty": "📭 Файл порожній",
    "err_pdf_module": "📄 PDF експорт потребує модуль fpdf2\n📦 Встановіть: pip install fpdf2",
    "err_file_not_created": "❌ Файл не було створено!",
    
    # Integrity
    "integrity_warn": "⚠️ Файл міг бути змінений. Продовжити?",
    "integrity_fail": "🚨 Файл пошкоджено! Відкриття скасовано",
    "integrity_ok": "✅ Цілісність файлу підтверджено",
    
    # About
    "about_text": "🔐 Професійний генератор паролів\nз відкритим вихідним кодом",
    "about_text_simple": "🔐 Професійний генератор паролів\n\n© Максим Мельников\n📜 MIT License",
    
    # Status
    "status_ok": "✅ Готово",
    "status_error": "❌ Помилка",
    "status_warning": "⚠️ Попередження",
    "please_wait": "⏳ Будь ласка, зачекайте...",
    
    # Diceware
    "diceware": "🎲 Diceware режим",
    "diceware_word_count": "📊 Кількість слів",
    "diceware_separator": "🔗 Розділювач",
    "diceware_words": "📝 Слова",
    
    # Password strength levels
    "password_strength_low": "🔴 Слабкий пароль",
    "password_strength_medium": "🟡 Середній пароль",
    "password_strength_high": "🟢 Надійний пароль",
    
    # Settings additional
    "settings_autosave": "💾 Автозбереження",
    "settings_rgb": "🌈 RGB анімація",
    "settings_sound_effect": "🔊 Звукові ефекти",
    "settings_auto_lock": "🔒 Автоблокування",
    "settings_corner_radius": "🔘 Закруглення кутів",
    "settings_font_size": "🔤 Розмір шрифту",
    "settings_clipboard_timeout": "📋 Таймаут буфера",
    
    # Settings profiles
    "settings_profiles": "💾 Профілі налаштувань",
    "settings_profiles_desc": "💾 Зберігайте та завантажуйте профілі налаштувань",
    "save_profile": "💾 Зберегти профіль",
    "load_profile": "📂 Завантажити профіль",
    "reset_profile": "🔄 Скинути",
    "profile_saved": "✅ Профіль налаштувань успішно збережено!",
    "profile_loaded": "✅ Профіль налаштувань успішно завантажено!",
    "profile_reset": "🔄 Налаштування скинуто до значень за замовчуванням!",
    "reset_profile_confirm": "⚠️ Скинути всі налаштування до значень за замовчуванням?",
    
    # Export/Save
    "export_title": "💾 Збереження",
    "export_text": "📄 Текстові файли",
    "export_password": "🔑 Файли паролів",
    "export_log": "📋 Файли логів",
    "export_pdf": "📑 PDF файли",
    "export_all": "📁 Всі файли",
    "file_saved": "✅ Файл збережено: {0}",
    
    # Import
    "import_title": "📂 Імпорт паролів",
    "import_format": "📁 Формат імпорту:",
    "import_warning": "⚠️ Імпортуйте тільки з перевірених джерел",
    "import_found": "🔍 Знайдено паролів",
    "import_confirm": "📥 Імпортувати?",
    "import_success": "✅ Імпортовано: {0}",
    "import_error": "❌ Помилка імпорту: {0}",
    "import_no_passwords": "📭 Не знайдено паролів у файлі",
    "import_all_files": "📁 Всі підтримувані файли",
    "import_csv": "📄 CSV файли",
    "import_json": "📄 JSON файли",
    "import_xml": "📄 KeePass XML файли",
    "import_1pux": "🔐 1Password 1PUX файли",
    "import_all": "📁 Всі файли",
    "imported": "📥 Імпортовано",
    "import_processing": "⏳ Обробка файлу...",
    "import_progress": "⏳ Імпорт...",
    "import_result": "📥 Імпортовано: {0}\n⏭️ Пропущено: {1}",
    
    # 2FA
    "2fa_title": "🔐 Двофакторна аутентифікація",
    "2fa_settings_title": "⚙️ Налаштування 2FA",
    "2fa_setup_title": "🔧 Налаштування 2FA",
    "2fa_verify_title": "✅ Підтвердження 2FA",
    "2fa_verify_disable": "🔑 Введіть код 2FA для підтвердження вимкнення:",
    "2fa_verify_regenerate": "🔄 Введіть код 2FA для генерації нових резервних кодів:",
    "2fa_enable": "🔒 Увімкнути 2FA",
    "2fa_disable": "🔓 Вимкнути 2FA",
    "2fa_status_enabled": "✅ Увімкнено",
    "2fa_status_disabled": "❌ Вимкнено",
    "2fa_description": "🔐 Двофакторна аутентифікація додає додатковий рівень безпеки.\n\nПри кожному вході в програму потрібно буде вводити 6-значний код із застосунку-аутентифікатора.",
    "2fa_scan_qr": "📱 Відскануйте цей QR-код застосунком-аутентифікатором:",
    "2fa_or_enter_manually": "✏️ Або введіть цей код вручну:",
    "2fa_enter_code": "🔢 Введіть код підтвердження:",
    "2fa_enter_verification": "🔢 Введіть код із застосунку-аутентифікатора:",
    "2fa_enter_backup": "🎫 Введіть резервний код (формат: XXXXXXXX):",
    "2fa_invalid_code": "❌ Невірний код підтвердження",
    "2fa_incorrect": "❌ Невірний код. Спробуйте ще раз",
    "2fa_enabled_success": "✅ Двофакторну аутентифікацію успішно увімкнено!\n\n💾 Збережіть резервні коди в надійному місці",
    "2fa_disabled_success": "✅ Двофакторну аутентифікацію вимкнено",
    "2fa_disable_confirm": "🔐 2FA вже увімкнена.\n\n❓ Ви хочете вимкнути її?",
    "2fa_disable_warning": "⚠️ УВАГА: Вимкнення 2FA зробить ваш акаунт менш захищеним!\n\n❓ Ви впевнені, що хочете вимкнути 2FA?",
    "2fa_master_required": "🔐 Спочатку встановіть майстер-пароль перед увімкненням 2FA",
    "2fa_setup_cancelled": "❌ Налаштування 2FA скасовано",
    "2fa_backup_codes": "📋 Резервні коди",
    "2fa_backup_codes_info": "🎫 Резервні коди",
    "2fa_backup_title": "🎫 Резервний код",
    "2fa_backup_warning": "⚠️ Збережіть резервні коди! Вони необхідні для відновлення доступу",
    "2fa_backup_warning_detailed": "⚠️ Збережіть ці коди в надійному місці!\n🔑 Кожен код можна використати лише один раз",
    "2fa_backup_count": "📊 Залишилось резервних кодів: {0}",
    "2fa_backup_used": "⚠️ Використано резервний код!\n🔄 Будь ласка, згенеруйте нові резервні коди в налаштуваннях",
    "2fa_invalid_try_backup": "❌ Невірний код.\n\n🎫 Використати резервний код?",
    "2fa_invalid_backup": "❌ Невірний резервний код",
    "2fa_regenerate_backup": "🔄 Згенерувати нові резервні коди",
    "2fa_backup_regenerated": "✅ Нові резервні коди успішно згенеровано",
    "2fa_regenerate_backup_confirm": "🔄 Генерація нових резервних кодів зробить старі недійсними.\n\n❓ Продовжити?",
    "2fa_error": "❌ Помилка верифікації 2FA",
    "2fa_missing_secret": "🔐 Секрет 2FA відсутній",
    "2fa_cancelled": "❌ Верифікацію 2FA скасовано",
    "2fa_module_error": "📦 Модуль 2FA недоступний",
    
    # QR module
    "qr_module_missing": "📱 Модуль qrcode не встановлено.\n📦 Встановіть: pip install qrcode[pil]",
    
    # Copy all
    "copy_all": "📋 Копіювати всі",
    
    # Settings search placeholder
    "settings_search_placeholder": "🔍 Пошук налаштувань...",
    
    # Open title
    "open_title": "📂 Виберіть файл пароля",
    
    # ========== NEW KEYS FOR MULTILANGUAGE FILE SAVING ==========
    "export_date": "📅 Дата",
    "export_password_label": "🔑 Пароль",
    
    # ========== NEW KEYS FOR PASSPHRASE GENERATOR ==========
    "passphrase_title": "🔐 Генератор парольних фраз (Diceware)",
    "passphrase_desc": "Генеруйте безпечні парольні фрази методом Diceware.\nКожне слово додає ~13 біт ентропії.\nФраза з 6 слів дає ~78 біт ентропії.",
    "passphrase_settings": "⚙️ Налаштування",
    "passphrase_word_count": "📊 Кількість слів",
    "passphrase_separator": "🔗 Розділювач",
    "passphrase_capitalize": "🔠 Великі літери",
    "passphrase_add_number": "🔢 Додати число",
    "passphrase_number_position": "📍 Позиція числа",
    "passphrase_position_start": "🏁 Початок",
    "passphrase_position_end": "🏁 Кінець",
    "passphrase_position_random": "🎲 Випадково",
    "passphrase_generate": "🎲 Згенерувати",
    "passphrase_copy_all": "📋 Копіювати всі",
    "passphrase_clear": "🗑️ Очистити",
    "passphrase_entropy": "🔢 Ентропія",
    "passphrase_generate_count": "🔢 Кількість фраз",
    "passphrase_nothing_to_copy": "📭 Нічого копіювати. Спочатку згенеруйте фрази.",
    "passphrase_copied_title": "✅ Скопійовано",
    "passphrase_copied": "✅ Парольні фрази скопійовані в буфер обміну!",
    "passphrase_error": "❌ Помилка генерації парольної фрази",

    # ========== v3 NEW FEATURES ==========
    "db_sort": "↕ Сортування",
    "db_sort_favorite": "⭐ Спочатку обрані",
    "db_sort_date_desc": "📅 Спочатку нові",
    "db_sort_date_asc": "📅 Спочатку старі",
    "db_sort_label_asc": "🔤 Назва А-Я",
    "db_sort_label_desc": "🔤 Назва Я-А",
    "db_sort_category": "🗂 За категоріями",
    "export_url": "🌐 URL",
    "export_username": "👤 Логін",
    "export_email": "📧 Email",
    "export_category": "🗂 Категорія",
    "export_kdbx": "🔐 KeePass (.kdbx)",
    "sync_title": "☁ Хмарна синхронізація",
    "sync_provider": "🌐 Провайдер",
    "sync_url": "🔗 URL сервера WebDAV",
    "sync_username": "👤 Логін",
    "sync_password": "🔑 Пароль",
    "sync_upload": "☁ Завантажити на сервер",
    "sync_download": "⬇ Скачати з сервера",
    "sync_test": "🔌 Перевірити з'єднання",
    "sync_strategy": "⚡ Стратегія",
    "sync_strat_upload": "☁ Завжди завантажувати",
    "sync_strat_download": "⬇ Завжди скачувати",
    "sync_strat_newest": "🕐 Використовувати найновіший",
    "sync_conn_ok": "✅ З'єднання успішне",
    "sync_conn_fail": "❌ З'єднання не вдалося",
    "sync_success_up": "✅ Базу даних завантажено на сервер",
    "sync_success_down": "✅ Базу даних скачано з сервера",
    "sync_error": "❌ Помилка синхронізації",
    "sync_no_lib": "⚠ Встановіть requests: pip install requests",
    "autotype_title": "⌨ Автовведення пароля",
    "autotype_btn": "⌨ Ввести пароль",
    "autotype_ok": "✅ Пароль введено",
    "autotype_fail": "❌ Помилка автовведення",
    "autotype_clip": "📋 Копіювати + Ctrl+V",
    "autotype_no_support": "⚠ Автовведення недоступне на цій системі",
    "vm_dev_mode": "🛠 DEV-режим: виявлення VM вимкнено",

    # copy URL/username buttons
    "db_copy_url": "🌐 Копіювати URL",
    "db_copy_username": "👤 Копіювати логін",
    "db_no_url": "URL не вказано",
    "db_no_username": "Логін не вказано",

    # cloud sync tab
    "tab_cloud": "☁ Хмара",
    "sync_desc": "Синхронізуйте зашифровану базу даних через WebDAV. Ключ ніколи не покидає пристрій.",
    "sync_security_note": "🔒 Синхронізується лише зашифрований файл — ключ залишається на пристрої",

    # --- additional v3 keys ---
    "db_edit_notes": "📝 Нотатки",
    "db_edit_password": "🔑 Пароль",
    "export_no_data": "Немає даних для експорту",
    "sync_save": "💾 Зберегти налаштування",
    "sync_dialog_title": "☁ Налаштування синхронізації",
    "sync_provider_header": "☁  Провайдер",
    "sync_provider_webdav": "🔗 Власний WebDAV",
    "sync_testing": "⏳ Перевірка з'єднання...",
    "sync_uploading": "⏳ Завантаження в хмару...",
    "sync_downloading": "⏳ Скачування з хмари...",
    "sync_not_configured": "❌ Не налаштовано",
    "sync_nextcloud_desc": "Ваш власний Nextcloud сервер",
    "sync_pcloud_desc": "Швейцарське хмарне сховище",
    "sync_box_desc": "Хмарне сховище Box",
    "sync_webdav_desc": "Будь-який WebDAV-сумісний сервер",
    "sync_placeholder_user": "ваш_логін",
    "select_all": "Всі",
    "select_none": "Зняти",
    "export_fields_btn": "Вибрати поля",
    "export_encoding_short": "Кодування:",
    "sync_hint": "ℹ Зашифрована база даних безпечна для будь-якого хмари",

    # --- New features ---
    "trash_btn": "🗑 Кошик",
    "trash_title": "🗑 Кошик",
    "trash_empty": "🗑 Очистити кошик",
    "trash_empty_confirm": "Видалити ВСІ елементи кошика назавжди?",
    "trash_empty_label": "Кошик порожній",
    "trash_deleted": "Видалено",
    "trash_restore": "↩ Відновити",
    "trash_del_perm": "✕ Видалити назавжди",
    "trash_perm_del": "Видалити назавжди?",
    "trash_items": "елементів",
    "trash_confirm": "До кошика?",
    "stats_btn": "📊 Статистика",
    "stats_title": "📊 Статистика сховища",
    "stats_total": "Всього записів",
    "stats_weak": "Слабкі паролі",
    "stats_dupl": "Дублів паролів",
    "stats_no_url": "Без URL",
    "stats_old_pwd": "Пароль старше 90 днів",
    "stats_in_trash": "У кошику",
    "stats_with_tags": "Записів з тегами",
    "stats_health": "Здоров'я сховища:",
    "bulk_btn": "☰  Дії для всіх  ▾",
    "bulk_select_all": "☑  Вибрати всі",
    "bulk_delete_all": "🗑  Видалити всі",
    "bulk_move_all": "📁  Перемістити всі",
    "bulk_export_all": "📤  Експорт усіх",
    "bulk_del_all_confirm": "Видалити ВСІ записи? Це не можна скасувати!",
    "bulk_move_title": "Перемістити всі до категорії",
    "bulk_move_label": "Категорія для ВСІХ записів:",
    "bulk_move_ph": "Введіть або виберіть",
    "bulk_select_info": "Усі записи обрані для дії.",
    "cf_title": "Дод. поля",
    "cf_name": "Назва поля",
    "cf_val": "Значення",
    "cf_hide": "Приховати",
    "cf_add": "+ Додати поле",
    "tags_title": "Теги",
    "tags_hint": "Через кому",
    "age_changed": "Пароль змінено",
    "db_duplicate": "⧉ Дублювати",
    "duplicate_prefix": "Копія",
    "qs_title": "Швидкий пошук",
    "qs_placeholder": "Введіть запит...",
    "db_trash_confirm": "До кошика?",
    "age_warn": "⚠ {d} дн.",
    "age_danger": "🔴 {d} дн.",
    "icon_eye_off": "🙈",
    "icon_eye": "👁",
    "icon_copy": "⧉",
    "icon_sync": "☁",
    "icon_stats": "📊",
    "icon_trash": "🗑",
    "icon_calendar": "📅",
    "icon_key": "🔑",
    "icon_success_sym": "✓",
    "icon_warning_sym": "⚠",
    "icon_question_sym": "?",
    "icon_info_sym": "ℹ",
    "icon_err": "✗",
    "icon_ok": "✓",
    "icon_danger": "🔴",
    "icon_warn": "⚠",
    "icon_search": "🔍",
    "icon_tag": "🏷",
    "icon_field": "🔧",
    "icon_date": "📅",
    "rating_stars": "★★★★★",
    "icon_close_sm": "✕",
    "icon_star_empty": "☆",
    "icon_star": "★",
    "icon_passphrase": "🔐",
    "copied_ok": "Скопійовано!",
}

# ==================== EXPORTS ====================

__all__: List[str] = [
    'UKRAINIAN_DICT',
]