"""
English language dictionary for Secure Pass Pro v4.0
Английский словарь для Secure Pass Pro v4.0
Англійський словник для Secure Pass Pro v4.0

FIXED: Added full type hints for dictionary
"""
from __future__ import annotations

from typing import Dict, List, Any, Optional

# ==================== ENGLISH DICTIONARY ====================

ENGLISH_DICT: Dict[str, str] = {
    # Main window
    "win_title": "🔐 Secure Pass Pro v4.0",
    "menu_title": "📋 Menu",
    "len": "📏 Length",
    "author": "👤 Author: Maxim Melnikov",
    "upper": "🔠 Uppercase",
    "lower": "🔡 Lowercase",
    "digits": "🔢 Digits",
    "symb": "✨ Special symbols",
    "ambig": "🚫 Exclude ambiguous",
    "unambig": "🚫 Exclude non-obvious",
    "at_least": "✅ Min 1 from each category",
    "hide": "👁 Hide symbols",
    "no_repeat": "🔄 Avoid consecutive repeated characters",
    "warn": "⚠️ Warning",
    "no_pwd": "⚠️ No password to save!",
    
    # Menu buttons
    "btn_gen": "🎲 Generate",
    "btn_name_gen": "👤 Name Generator",
    "btn_passphrase": "🔐 Passphrase",
    "btn_copy": "📋 Copy password",
    "btn_save": "💾 Save to file",
    "btn_open": "📂 Open file",
    "btn_qr": "📱 QR Code",
    "btn_hist": "📜 History",
    "btn_db": "🗄 Password vault",
    "btn_hibp": "🔍 Check leaks",
    "btn_upd": "🔄 Update",
    "btn_settings": "⚙️ Settings",
    "btn_about": "ℹ️ About",
    "btn_clear_hist": "🗑️ Clear history",
    "btn_eye": "👁",
    "btn_eye_closed": "🙈",
    
    # Tooltips
    "tt_gen": "🎲 Create a new random password (F5)",
    "tt_name_gen": "👤 Generate names for any purpose",
    "tt_passphrase": "🔐 Generate passphrase (Diceware)\nEach word adds ~13 bits of entropy",
    "tt_copy": "📋 Copy to clipboard (clears in {0} sec)",
    "tt_save": "💾 Save current password to file (Ctrl+S)",
    "tt_open": "📂 Open password from file (Ctrl+O)",
    "tt_qr": "📱 Create QR code for quick scanning",
    "tt_hist": "📜 Show last 50 passwords",
    "tt_db": "🗄️ Open password vault",
    "tt_hibp": "🔍 Check password against breach database",
    "tt_upd": "🔄 Check for new version",
    "tt_about": "ℹ️ Program information",
    "tt_settings": "⚙️ Application settings",
    "tt_eye": "👁 Show / hide password",
    "tt_no_repeat": "🔄 Prevent consecutive repeated characters",
    "tt_auto_lock": "🔒 Auto lock on inactivity",
    "tt_clip_timeout": "⏱️ Seconds before clipboard is cleared",
    
    # Name generator
    "name_gen_title": "👤 Name Generator",
    "name_gen_type_label": "📋 Generation type",
    "name_gen_samp": "🎮 SAMP RP",
    "name_gen_email": "📧 Email address",
    "name_gen_game": "🎮 Game nickname",
    "name_gen_cool": "😎 Cool nickname",
    "name_gen_beauty": "✨ Beautiful nickname",
    "name_gen_short": "📏 Short (3-5)",
    "name_gen_long": "📏 Long (8+)",
    "name_gen_random": "🎲 Random",
    "name_gen_settings_label": "⚙️ Settings",
    "name_gen_gender": "👤 Gender:",
    "name_gen_male": "👨 Male",
    "name_gen_female": "👩 Female",
    "name_gen_random_gender": "🎲 Random",
    "name_gen_lang": "🌐 Language:",
    "name_gen_russian": "🇷🇺 Russian",
    "name_gen_english": "🇬🇧 English",
    "name_gen_separator": "🔗 Separator:",
    "name_gen_separator_yes": "✅ YES (_)",
    "name_gen_separator_no": "❌ NO",
    "name_gen_count": "🔢 Count:",
    "name_gen_generate_btn": "🎲 Generate",
    "name_gen_clear_btn": "🗑️ Clear",
    "name_gen_copy_btn": "📋 Copy all",
    "name_gen_result_label": "📝 Result",
    "name_gen_copied": "✅ Copied {0} names!",
    "name_gen_generating": "⏳ Generating...",
    "name_gen_error": "❌ Name generation error",
    
    # Password strength
    "strength": "🔒 Strength: ~{0} combos",
    "crack_time": "⏱️ {0}",
    "time_sec": "⚡ seconds to crack",
    "time_day": "📅 days to crack",
    "time_year": "📆 years to crack",
    "time_cent": "🏛️ centuries to crack",
    "st_low": "🔴 Weak password",
    "st_mid": "🟡 Medium password",
    "st_high": "🟢 Strong password",
    "strength_weak": "Weak",
    "strength_medium": "Medium",
    "strength_medium_plus": "Medium+",
    "strength_strong": "Strong",
    
    # Settings window
    "settings_search": "🔍 Search settings...",
    "settings_title": "⚙️ Settings",
    "settings_subtitle": "⚙️ Configure the app to your needs",
    "settings_lang": "🌐 Interface language",
    "settings_lang_desc": "🌐 Choose interface language",
    "settings_sound": "🔊 App sound",
    "settings_theme": "🎨 Appearance theme",
    "settings_theme_desc": "🎨 Choose application appearance",
    "settings_radius": "🔘 Corner radius",
    "radius_desc": "🔘 Corner rounding of elements",
    "font_size": "🔤 Font size",
    "font_size_desc": "🔤 Interface text size",
    "theme_sys": "💻 System",
    "theme_dark": "🌙 Dark",
    "theme_light": "☀️ Light",
    "sound_on": "🔊 Sound: on",
    "sound_off": "🔇 Sound: off",
    "sound_desc": "🔊 Sound effects for actions",
    "close": "❌ Close",
    "ok": "✅ OK",
    "cancel": "❌ Cancel",
    "yes": "✅ Yes",
    "no": "❌ No",
    "save": "💾 Save",
    "delete": "🗑 Delete",
    "edit": "✏ Edit",
    "copy": "📋 Copy",
    "clear": "🗑️ Clear",
    "back": "🔙 Back",
    "next": "➡️ Next",
    "finish": "✅ Finish",
    "apply": "✅ Apply",
    "reset": "🔄 Reset",
    "refresh": "🔄 Refresh",
    "tab_design": "🎨 Design",
    "tab_security": "🔒 Security",
    "tab_general": "⚙️ General",
    "tab_cloud": "☁ Cloud",
    
    # RGB Settings
    "rgb_label": "🌈 RGB border",
    "rgb_label_desc": "🌈 Colorful border animation",
    "rgb_on": "✅ On",
    "rgb_off": "❌ Off",
    "rgb_speed": "⚡ RGB Speed",
    "rgb_speed_desc": "⚡ Animation speed",
    "rgb_speed_slow": "🐢 Slow",
    "rgb_speed_normal": "⚡ Normal",
    "rgb_speed_fast": "🚀 Fast",
    "rgb_width": "📏 RGB Width",
    "rgb_width_desc": "📏 Border thickness",
    "rgb_width_thin": "➖ Thin",
    "rgb_width_normal": "➖➖ Normal",
    "rgb_width_thick": "🔲 Thick",
    
    # Auto save
    "auto_save": "💾 Auto save",
    "auto_save_desc": "💾 Automatically save passwords",
    "auto_save_on": "✅ On",
    "auto_save_off": "❌ Off",
    "auto_save_enabled": "✅ Auto save enabled",
    "auto_save_disabled": "❌ Auto save disabled",
    "auto_save_label": "💾 Auto save",
    
    # Auto lock
    "auto_lock": "🔒 Auto lock",
    "auto_lock_desc": "🔒 Auto lock on inactivity",
    "auto_lock_timeout": "⏰ Lock timeout: {0} min",
    "auto_lock_title": "🔒 Program locked",
    "unlock": "🔓 Unlock",
    
    # Clipboard
    "clip_timeout": "📋 Clipboard clear: {0} sec",
    "clip_timeout_desc": "📋 Auto clear clipboard",
    "clipboard_cleared": "✅ Clipboard cleared",
    "clipboard_auto_clear": "📋 Auto clear clipboard in {0} sec",
    "clear_clipboard": "🗑️ Clear clipboard",
    "pwd_done": "✅ Password copied",
    "copied": "✅ Copied! ({0}s)",
    
    # Master password
    "master_title": "🔐 Master password",
    "master_desc": "🔐 Program access protection",
    "master_prompt": "🔑 Enter master password:",
    "master_set_title": "🔐 Set master password",
    "master_set_prompt": "🔑 Create master password:",
    "master_confirm": "✅ Confirm master password:",
    "master_mismatch": "❌ Passwords do not match",
    "master_wrong": "❌ Wrong password! Attempt {0} of {1}",
    "master_blocked": "🚫 Too many attempts. Program closed",
    "master_set_ok": "✅ Master password set",
    "master_removed": "✅ Master password removed",
    "master_btn_set": "🔐 Set master password",
    "master_btn_remove": "🗑️ Remove master password",
    "master_current": "📊 Status:",
    "master_status_set": "✅ Set",
    "master_status_not_set": "❌ Not set",
    "master_remove_confirm": "⚠️ Remove master password?",
    "master_remove_prompt": "🔑 Enter current master password:",
    "master_not_set": "❌ Master password not set",
    "master_already_set": "✅ Master password already set",
    "master_set_error": "❌ Failed to set master password",
    "master_remove_error": "❌ Failed to remove master password",
    "master_status_text": "🔐 Master password: set",
    "master_status_not_set_text": "⚠️ Master password: not set",
    "master_too_short": "⚠️ Password too short. Minimum 8 characters",
    "master_weak": "⚠️ Password too weak. Add a digit or special character",
    "master_verified": "✅ Master password verified",
    
    # Database window
    "db_title": "🗄️ Password vault",
    "db_search": "🔍 Search",
    "db_search_placeholder": "🔍 Search by label, password, URL, username, email...",
    "db_save_current": "💾 Save current password",
    "db_save_current_btn": "💾 Save current password",
    "db_saved": "✅ Password saved!",
    "db_save_success": "✅ Password saved!",
    "db_no_pass": "❌ Generate a password first!",
    "db_count": "📊 Records: {0}",
    "db_empty": "📭 Vault is empty",
    "db_no_label": "🏷️ No label",
    "db_edit_title": "✏️ Edit record",
    "db_edit_label": "📝 Label",
    "db_edit_pass": "🔑 Password",
    "db_edit_url": "🔗 URL / Website",
    "db_edit_username": "👤 Username",
    "db_edit_email": "📧 Email",
    "db_edit_category": "📁 Category",
    "db_edit_favorite": "⭐ Favorite",
    "db_category_filter": "📁 Category",
    "db_favorites_only": "⭐ Favorites only",
    "db_copy": "Copy",
    "db_edit": "Edit",
    "db_delete": "Delete",
    "db_del_confirm": "🗑️ Delete this record?",
    "db_delete_success": "✅ Record deleted!",
    "db_import": "📂 Import passwords",
    "db_label_prompt": "🏷️ Label:",
    "db_save_error": "❌ Save error",
    "db_delete_error": "❌ Delete error",
    "db_search_no_results": "🔍 No results found",
    "db_notes": "📝 Notes",
    
    # History
    "hist_empty": "📭 History is empty",
    
    # PDF
    "pdf_date": "Date",
    "pdf_pass": "Password",
    "pdf_theme": "📄 PDF Theme",
    "pdf_theme_desc": "📄 PDF export appearance",
    "pdf_theme_light": "☀️ Light",
    "pdf_theme_dark": "🌙 Dark",
    
    # QR
    "qr_closes_in": "⏰ Window closes in",
    "seconds_short": "sec",
    
    # Lock screen
    "lock_screen_title": "🔒 Enter master password",
    "lock_wait": "⏳ Please wait",
    
    # HIBP
    "hibp_no_password": "⚠️ Generate a password first",
    "hibp_checking": "🔍 Checking...",
    "hibp_safe": "✅ Password is safe",
    "hibp_found": "❌ Password found in {count} breaches",
    "hibp_error": "⚠️ Check error",
    "hibp_error_title": "❌ Check error",
    "hibp_safe_title": "✅ Password is safe",
    "hibp_found_title": "🚨 WARNING! Password compromised",
    "hibp_warning": "⚠️ Change your password immediately",
    "hibp_rate_limit": "⏳ Please wait {0} seconds before next check.\nThis protects the server from overload.",
    "hibp_check_error": "❌ Could not connect to server.\nPlease check your internet connection.",
    "hibp_safe_message": "🔒 Password not found in breach databases.\n\nSafe to use.",
    "hibp_found_message": "⚠️ Password found {0} time(s) in breaches!\n\nGenerate a new password.",
    "hibp_change_password": "🔑 It is recommended to change your password immediately!",
    "hibp_generate_new": "🔄 Generate new password",
    "hibp_close": "❌ Close",
    "hibp_checking_title": "🔍 Checking password...",
    "hibp_result_title": "🔍 Breach check result",
    "hibp_check_button": "🔍 Check leaks",
    "hibp_checking_status": "🔍 Checking...",
    
    # Update
    "update_check": "🔄 Check for updates",
    "update_available": "📦 Version {0} available",
    "update_not_available": "✅ Latest version installed",
    "update_available_title": "📦 Update available",
    "update_confirm_title": "🔄 Update",
    "update_confirm_message": "📥 Install update?",
    "update_error": "❌ Update error",
    "update_signature_error": "❌ Update signature verification failed!",
    "update_integrity_error": "❌ Update integrity check failed!",
    "update_restart": "✅ Update downloaded successfully!\n\n🔄 The application will restart to apply changes.",
    "download_start": "📥 Downloading update...",
    "update_installing": "⚙️ Installing update...",
    "update_rollback": "⏪ Rollback performed",
    "update_rollback_message": "⚠️ Installation failed, rolled back to previous version.",
    "update_cancelled": "❌ Update cancelled",
    "update_no_backup": "📭 No saved backups for rollback.",
    "update_rollback_confirm": "⚠️ Are you sure you want to rollback to the previous version?\n\nAny unsaved changes will be lost.",
    "update_rollback_success": "✅ Rollback completed successfully.\n\n🔄 The application will restart.",
    "update_rollback_error": "❌ Failed to rollback.",
    "update_info": "ℹ️ Current version: {0}",
    "update_date": "📅 Date",
    "update_size": "📦 Size",
    
    # Security
    "security": "🔒 Security",
    "security_audit_pass": "✅ Security check passed",
    "security_audit_fail": "⚠️ Security issues detected",
    "wiki_link": "📖 Wiki",
    "rate_limit_warning": "⚠️ 'No repeats' mode reduces strength",
    "duplicate_warning": "⚠️ This password already exists in the database.\n\n💾 Save anyway?",
    "skip_duplicates": "⏭️ Skip duplicate passwords",
    "continue_anyway": "⚠️ Continue anyway?",
    "truncate_question": "✂️ Truncate to {0} characters?",
    
    # SQLCipher
    "sqlcipher_enabled": "✅ SQLCipher enabled",
    "sqlcipher_disabled": "❌ SQLCipher disabled",
    
    # Errors
    "err_cat": "⚠️ Select at least one category",
    "err_pool_small": "⚠️ Too few available characters",
    "err_save": "❌ Save failed: {0}",
    "err_open": "❌ Could not read file: {0}",
    "err_unsupported": "❌ Unsupported file type: {0}",
    "err_integrity": "🚨 Critical error: File corrupted",
    "err_no_repeat": "⚠️ Could not generate password without repeats",
    "err_no_repeat_fallback": "\n⚠️ Password with repeats used",
    "err_title": "❌ Error",
    "err_encrypt": "🔒 Encryption error",
    "err_decrypt": "🔓 Decryption error",
    "err_database": "🗄️ Database error",
    "err_network": "🌐 Network error",
    "err_permission": "🔐 Permission error",
    "err_copy": "📋 Copy error",
    "err_qr": "📱 QR code error",
    "err_timeout": "⏰ Connection timeout",
    "err_import": "❌ Module import error",
    "err_file_too_large": "📁 File too large",
    "err_invalid_format": "📄 Invalid file format",
    "err_malformed": "💥 File corrupted",
    "err_encoding": "🔤 Unsupported file encoding",
    "err_file_empty": "📭 File is empty",
    "err_pdf_module": "📄 PDF export requires fpdf2 module\n📦 Install: pip install fpdf2",
    "err_file_not_created": "❌ File was not created!",
    
    # Integrity
    "integrity_warn": "⚠️ File may have been modified. Continue?",
    "integrity_fail": "🚨 File corrupted! Opening cancelled",
    "integrity_ok": "✅ File integrity verified",
    
    # About
    "about_text": "🔐 Professional password generator\nwith open source code",
    "about_text_simple": "🔐 Professional password generator\n\n© Maxim Melnikov\n📜 MIT License",
    
    # Status
    "status_ok": "✅ Done",
    "status_error": "❌ Error",
    "status_warning": "⚠️ Warning",
    "please_wait": "⏳ Please wait...",
    
    # Diceware
    "diceware": "🎲 Diceware mode",
    "diceware_word_count": "📊 Word count",
    "diceware_separator": "🔗 Separator",
    "diceware_words": "📝 Words",
    
    # Password strength levels
    "password_strength_low": "🔴 Weak password",
    "password_strength_medium": "🟡 Medium password",
    "password_strength_high": "🟢 Strong password",
    
    # Settings additional
    "settings_autosave": "💾 Auto save",
    "settings_rgb": "🌈 RGB animation",
    "settings_sound_effect": "🔊 Sound effects",
    "settings_auto_lock": "🔒 Auto lock",
    "settings_corner_radius": "🔘 Corner radius",
    "settings_font_size": "🔤 Font size",
    "settings_clipboard_timeout": "📋 Clipboard timeout",
    
    # Settings profiles
    "settings_profiles": "💾 Settings Profiles",
    "settings_profiles_desc": "💾 Save and load settings profiles",
    "save_profile": "💾 Save Profile",
    "load_profile": "📂 Load Profile",
    "reset_profile": "🔄 Reset",
    "profile_saved": "✅ Settings profile saved successfully!",
    "profile_loaded": "✅ Settings profile loaded successfully!",
    "profile_reset": "🔄 Settings reset to defaults!",
    "reset_profile_confirm": "⚠️ Reset all settings to defaults?",
    
    # Export/Save
    "export_title": "💾 Save",
    "export_text": "📄 Text Files",
    "export_password": "🔑 Password Files",
    "export_log": "📋 Log Files",
    "export_pdf": "📑 PDF Files",
    "export_all": "📁 All Files",
    "file_saved": "✅ File saved: {0}",
    
    # Import
    "import_title": "📂 Import Passwords",
    "import_format": "📁 Import format:",
    "import_warning": "⚠️ Import only from trusted sources",
    "import_found": "🔍 Passwords found",
    "import_confirm": "📥 Import?",
    "import_success": "✅ Imported: {0}",
    "import_error": "❌ Import error: {0}",
    "import_no_passwords": "📭 No passwords found in file",
    "import_all_files": "📁 All Supported Files",
    "import_csv": "📄 CSV Files",
    "import_json": "📄 JSON Files",
    "import_xml": "📄 KeePass XML Files",
    "import_1pux": "🔐 1Password 1PUX Files",
    "import_all": "📁 All Files",
    "imported": "📥 Imported",
    "import_processing": "⏳ Processing file...",
    "import_progress": "⏳ Importing...",
    "import_result": "📥 Imported: {0}\n⏭️ Skipped: {1}",
    
    # 2FA
    "2fa_title": "🔐 Two-Factor Authentication",
    "2fa_settings_title": "⚙️ 2FA Settings",
    "2fa_setup_title": "🔧 2FA Setup",
    "2fa_verify_title": "✅ 2FA Verification",
    "2fa_verify_disable": "🔑 Enter 2FA code to confirm disabling:",
    "2fa_verify_regenerate": "🔄 Enter 2FA code to generate new backup codes:",
    "2fa_enable": "🔒 Enable 2FA",
    "2fa_disable": "🔓 Disable 2FA",
    "2fa_status_enabled": "✅ Enabled",
    "2fa_status_disabled": "❌ Disabled",
    "2fa_description": "🔐 Two-Factor Authentication adds an extra layer of security.\n\nEach time you unlock the program, you will need to enter a 6-digit code from an authenticator app.",
    "2fa_scan_qr": "📱 Scan this QR code with your authenticator app:",
    "2fa_or_enter_manually": "✏️ Or enter this code manually:",
    "2fa_enter_code": "🔢 Enter verification code:",
    "2fa_enter_verification": "🔢 Enter code from authenticator app:",
    "2fa_enter_backup": "🎫 Enter backup code (format: XXXXXXXX):",
    "2fa_invalid_code": "❌ Invalid verification code",
    "2fa_incorrect": "❌ Incorrect code. Please try again",
    "2fa_enabled_success": "✅ Two-Factor Authentication has been enabled successfully!\n\n💾 Please save your backup codes in a safe place",
    "2fa_disabled_success": "✅ Two-Factor Authentication has been disabled",
    "2fa_disable_confirm": "🔐 2FA is already enabled.\n\n❓ Do you want to disable it?",
    "2fa_disable_warning": "⚠️ WARNING: Disabling 2FA will make your account less secure!\n\n❓ Are you sure you want to disable 2FA?",
    "2fa_master_required": "🔐 Please set a master password before enabling 2FA",
    "2fa_setup_cancelled": "❌ 2FA setup cancelled",
    "2fa_backup_codes": "📋 Backup Codes",
    "2fa_backup_codes_info": "🎫 Backup Codes",
    "2fa_backup_title": "🎫 Backup Code",
    "2fa_backup_warning": "⚠️ Save backup codes! They are required to recover access",
    "2fa_backup_warning_detailed": "⚠️ Store these codes in a safe place!\n🔑 Each code can be used only once",
    "2fa_backup_count": "📊 Remaining backup codes: {0}",
    "2fa_backup_used": "⚠️ Backup code used!\n🔄 Please generate new backup codes in settings",
    "2fa_invalid_try_backup": "❌ Invalid code.\n\n🎫 Do you want to use a backup code?",
    "2fa_invalid_backup": "❌ Invalid backup code",
    "2fa_regenerate_backup": "🔄 Generate New Backup Codes",
    "2fa_backup_regenerated": "✅ New backup codes generated successfully",
    "2fa_regenerate_backup_confirm": "🔄 Generating new backup codes will invalidate old ones.\n\n❓ Continue?",
    "2fa_error": "❌ 2FA verification error",
    "2fa_missing_secret": "🔐 2FA secret missing",
    "2fa_cancelled": "❌ 2FA verification cancelled",
    "2fa_module_error": "📦 2FA module unavailable",
    
    # QR module
    "qr_module_missing": "📱 QR code module not installed.\n📦 Install: pip install qrcode[pil]",
    
    # Copy all
    "copy_all": "📋 Copy All",
    
    # Settings search placeholder
    "settings_search_placeholder": "🔍 Search settings...",
    
    # Open title
    "open_title": "📂 Select password file",
    
    # ========== NEW KEYS FOR MULTILANGUAGE FILE SAVING ==========
    "export_date": "📅 Date",
    "export_password_label": "🔑 Password",
    
    # ========== NEW KEYS FOR PASSPHRASE GENERATOR ==========
    "passphrase_title": "🔐 Passphrase Generator (Diceware)",
    "passphrase_desc": "Generate secure passphrases using the Diceware method.\nEach word adds ~13 bits of entropy.\nA 6-word passphrase provides ~78 bits of entropy.",
    "passphrase_settings": "⚙️ Settings",
    "passphrase_word_count": "📊 Word count",
    "passphrase_separator": "🔗 Separator",
    "passphrase_capitalize": "🔠 Capitalize each word",
    "passphrase_add_number": "🔢 Add a random number",
    "passphrase_number_position": "📍 Number position",
    "passphrase_position_start": "🏁 Start",
    "passphrase_position_end": "🏁 End",
    "passphrase_position_random": "🎲 Random",
    "passphrase_generate": "🎲 Generate",
    "passphrase_copy_all": "📋 Copy All",
    "passphrase_clear": "🗑️ Clear",
    "passphrase_entropy": "🔢 Entropy",
    "passphrase_generate_count": "🔢 Number of phrases",
    "passphrase_nothing_to_copy": "📭 Nothing to copy. Generate passphrases first.",
    "passphrase_copied_title": "✅ Copied",
    "passphrase_copied": "✅ Passphrases copied to clipboard!",
    "passphrase_error": "❌ Failed to generate passphrase",

    # ========== v3 NEW FEATURES ==========
    "db_sort": "↕ Sort by",
    "db_sort_favorite": "⭐ Favorites first",
    "db_sort_date_desc": "📅 Newest first",
    "db_sort_date_asc": "📅 Oldest first",
    "db_sort_label_asc": "🔤 Label A-Z",
    "db_sort_label_desc": "🔤 Label Z-A",
    "db_sort_category": "🗂 By category",
    "export_url": "🌐 URL",
    "export_username": "👤 Username",
    "export_email": "📧 Email",
    "export_category": "🗂 Category",
    "export_kdbx": "🔐 KeePass (.kdbx)",
    "sync_title": "☁ Cloud Sync",
    "sync_provider": "🌐 Provider",
    "sync_url": "🔗 WebDAV server URL",
    "sync_username": "👤 Username",
    "sync_password": "🔑 Password",
    "sync_upload": "☁ Upload to server",
    "sync_download": "⬇ Download from server",
    "sync_test": "🔌 Test connection",
    "sync_strategy": "⚡ Strategy",
    "sync_strat_upload": "☁ Always upload",
    "sync_strat_download": "⬇ Always download",
    "sync_strat_newest": "🕐 Use newest",
    "sync_conn_ok": "✅ Connection successful",
    "sync_conn_fail": "❌ Connection failed",
    "sync_success_up": "✅ Database uploaded to server",
    "sync_success_down": "✅ Database downloaded from server",
    "sync_error": "❌ Sync error",
    "sync_no_lib": "⚠ Install requests: pip install requests",
    "autotype_title": "⌨ Password Auto-Type",
    "autotype_btn": "⌨ Type password",
    "autotype_ok": "✅ Password typed",
    "autotype_fail": "❌ Auto-type error",
    "autotype_clip": "📋 Copy + Ctrl+V",
    "autotype_no_support": "⚠ Auto-type not available on this system",
    "vm_dev_mode": "🛠 DEV mode: VM detection disabled",

    # copy URL/username buttons
    "db_copy_url": "🌐 Copy URL",
    "db_copy_username": "👤 Copy Login",
    "db_no_url": "URL not set",
    "db_no_username": "Username not set",

    # cloud sync tab
    "tab_cloud": "☁ Cloud",
    "sync_desc": "Sync your encrypted database via WebDAV. Your key never leaves the device.",
    "sync_security_note": "🔒 Only the encrypted file is synced — your key never leaves the device",

    # --- additional v3 keys ---
    "db_edit_notes": "📝 Notes",
    "db_edit_password": "🔑 Password",
    "export_no_data": "No data to export",
    "sync_save": "💾 Save settings",
    "sync_dialog_title": "☁ Sync Settings",
    "sync_provider_header": "☁  Provider",
    "sync_provider_webdav": "🔗 Custom WebDAV",
    "sync_testing": "⏳ Testing connection...",
    "sync_uploading": "⏳ Uploading to cloud...",
    "sync_downloading": "⏳ Downloading from cloud...",
    "sync_not_configured": "❌ Not configured",
    "sync_nextcloud_desc": "Your own Nextcloud server",
    "sync_pcloud_desc": "Swiss cloud storage",
    "sync_box_desc": "Box cloud storage",
    "sync_webdav_desc": "Any WebDAV-compatible server",
    "sync_placeholder_user": "your_login",
    "select_all": "All",
    "select_none": "Clear",
    "export_fields_btn": "Select fields",
    "export_encoding_short": "Encoding:",
    "sync_hint": "ℹ The encrypted database is safe for any cloud",

    # --- New features ---
    "trash_btn": "🗑 Trash",
    "trash_title": "🗑 Trash",
    "trash_empty": "🗑 Empty Trash",
    "trash_empty_confirm": "Permanently delete ALL items in Trash?",
    "trash_empty_label": "Trash is empty",
    "trash_deleted": "Deleted",
    "trash_restore": "↩ Restore",
    "trash_del_perm": "✕ Delete permanently",
    "trash_perm_del": "Delete permanently?",
    "trash_items": "items",
    "trash_confirm": "Move to Trash?",
    "stats_btn": "📊 Stats",
    "stats_title": "📊 Vault Statistics",
    "stats_total": "Total records",
    "stats_weak": "Weak passwords",
    "stats_dupl": "Duplicate passwords",
    "stats_no_url": "No URL set",
    "stats_old_pwd": "Password ≥ 90 days old",
    "stats_in_trash": "In Trash",
    "stats_with_tags": "Records with tags",
    "stats_health": "Vault health:",
    "bulk_btn": "☰  Actions for all  ▾",
    "bulk_select_all": "☑  Select All",
    "bulk_delete_all": "🗑  Delete All",
    "bulk_move_all": "📁  Move All",
    "bulk_export_all": "📤  Export All",
    "bulk_del_all_confirm": "DELETE ALL records? Cannot be undone!",
    "bulk_move_title": "Move all to category",
    "bulk_move_label": "Set category for ALL records:",
    "bulk_move_ph": "Type or pick",
    "bulk_select_info": "All records selected for action.",
    "cf_title": "Custom Fields",
    "cf_name": "Field name",
    "cf_val": "Value",
    "cf_hide": "Hide",
    "cf_add": "+ Add field",
    "tags_title": "Tags",
    "tags_hint": "Comma-separated",
    "age_changed": "Password changed",
    "db_duplicate": "⧉ Duplicate",
    "duplicate_prefix": "Copy of",
    "qs_title": "Quick Search",
    "qs_placeholder": "Type to search...",
    "db_trash_confirm": "Move to Trash?",
    "age_warn": "⚠ {d} days old",
    "age_danger": "🔴 {d} days old",
    "icon_eye_off": "🙈",
    "icon_eye": "👁",
    "icon_copy": "⧉",
    "icon_sync": "☁",
    "icon_stats": "📊",
    "icon_trash": "🗑",
    "icon_calendar": "📅",
    "icon_key": "🔑",
    "icon_success_sym": "✓",
    "icon_warning_sym": "⚠",
    "icon_question_sym": "?",
    "icon_info_sym": "ℹ",
    "icon_err": "✗",
    "icon_ok": "✓",
    "icon_danger": "🔴",
    "icon_warn": "⚠",
    "icon_search": "🔍",
    "icon_tag": "🏷",
    "icon_field": "🔧",
    "icon_date": "📅",
    "rating_stars": "★★★★★",
    "icon_close_sm": "✕",
    "icon_star_empty": "☆",
    "icon_star": "★",
    "icon_passphrase": "🔐",
    "copied_ok": "Copied!",
}

# ==================== EXPORTS ====================

__all__: List[str] = [
    'ENGLISH_DICT',
]