"""
Russian language dictionary for Secure Pass Pro v4.0
Русский словарь для Secure Pass Pro v4.0
Російський словник для Secure Pass Pro v4.0

FIXED: Added full type hints for dictionary
"""
from __future__ import annotations

from typing import Dict, List, Any, Optional

# ==================== RUSSIAN DICTIONARY ====================

RUSSIAN_DICT: Dict[str, str] = {
    # Main window
    "win_title": "🔐 Secure Pass Pro v4.0",
    "menu_title": "📋 Меню",
    "len": "📏 Длина",
    "author": "👤 Автор: Максим Мельников",
    "upper": "🔠 Заглавные буквы",
    "lower": "🔡 Строчные буквы",
    "digits": "🔢 Цифры",
    "symb": "✨ Спецсимволы",
    "ambig": "🚫 Исключить похожие",
    "unambig": "🚫 Исключить неоднозначные",
    "at_least": "✅ Минимум 1 из каждой категории",
    "hide": "👁 Скрывать символы",
    "no_repeat": "🔄 Избегать повторов символов подряд",
    "warn": "⚠️ Внимание",
    "no_pwd": "⚠️ Нет пароля для сохранения!",
    
    # Menu buttons
    "btn_gen": "🎲 Сгенерировать",
    "btn_name_gen": "👤 Генератор имён",
    "btn_passphrase": "🔐 Парольная фраза",
    "btn_copy": "📋 Копировать пароль",
    "btn_save": "💾 Сохранить в файл",
    "btn_open": "📂 Открыть файл",
    "btn_qr": "📱 QR-код",
    "btn_hist": "📜 История",
    "btn_db": "🗄 База паролей",
    "btn_hibp": "🔍 Проверить утечки",
    "btn_upd": "🔄 Обновить",
    "btn_settings": "⚙️ Настройки",
    "btn_about": "ℹ️ О программе",
    "btn_clear_hist": "🗑️ Очистить историю",
    "btn_eye": "👁",
    "btn_eye_closed": "🙈",
    
    # Tooltips
    "tt_gen": "🎲 Создать новый случайный пароль",
    "tt_name_gen": "👤 Генерация имён для любых целей",
    "tt_passphrase": "🔐 Генерация парольной фразы (Diceware)\nКаждое слово добавляет ~13 бит энтропии",
    "tt_copy": "📋 Копировать в буфер (очистка через {0} сек)",
    "tt_save": "💾 Сохранить текущий пароль в файл",
    "tt_open": "📂 Открыть пароль из файла",
    "tt_qr": "📱 Создать QR-код для быстрого сканирования",
    "tt_hist": "📜 Показать последние 50 паролей",
    "tt_db": "🗄️ Открыть хранилище паролей",
    "tt_hibp": "🔍 Проверить пароль в базе утечек",
    "tt_upd": "🔄 Проверить наличие новой версии",
    "tt_about": "ℹ️ Информация о программе",
    "tt_settings": "⚙️ Настройки приложения",
    "tt_eye": "👁 Показать / скрыть пароль",
    "tt_no_repeat": "🔄 Не допускать одинаковых символов подряд",
    "tt_auto_lock": "🔒 Автоматическая блокировка при бездействии",
    "tt_clip_timeout": "⏱️ Через сколько секунд буфер обмена будет очищен",
    
    # Name generator
    "name_gen_title": "👤 Генератор имён",
    "name_gen_type_label": "📋 Тип генерации",
    "name_gen_samp": "🎮 SAMP RP",
    "name_gen_email": "📧 Email адрес",
    "name_gen_game": "🎮 Игровой ник",
    "name_gen_cool": "😎 Крутой ник",
    "name_gen_beauty": "✨ Красивый ник",
    "name_gen_short": "📏 Короткий (3-5)",
    "name_gen_long": "📏 Длинный (8+)",
    "name_gen_random": "🎲 Случайный",
    "name_gen_settings_label": "⚙️ Настройки",
    "name_gen_gender": "👤 Пол:",
    "name_gen_male": "👨 Мужской",
    "name_gen_female": "👩 Женский",
    "name_gen_random_gender": "🎲 Случайный",
    "name_gen_lang": "🌐 Язык:",
    "name_gen_russian": "🇷🇺 Русский",
    "name_gen_english": "🇬🇧 English",
    "name_gen_separator": "🔗 Разделитель:",
    "name_gen_separator_yes": "✅ ДА (_)",
    "name_gen_separator_no": "❌ НЕТ",
    "name_gen_count": "🔢 Количество:",
    "name_gen_generate_btn": "🎲 Сгенерировать",
    "name_gen_clear_btn": "🗑️ Очистить",
    "name_gen_copy_btn": "📋 Копировать всё",
    "name_gen_result_label": "📝 Результат",
    "name_gen_copied": "✅ Скопировано {0} имён!",
    "name_gen_generating": "⏳ Генерация...",
    "name_gen_error": "❌ Ошибка генерации имён",
    
    # Password strength
    "strength": "🔒 Стойкость: ~{0} вариантов",
    "crack_time": "⏱️ {0}",
    "time_sec": "⚡ секунды на взлом",
    "time_day": "📅 дни на взлом",
    "time_year": "📆 годы на взлом",
    "time_cent": "🏛️ столетия на взлом",
    "st_low": "🔴 Слабый пароль",
    "st_mid": "🟡 Средний пароль",
    "st_high": "🟢 Надёжный пароль",
    "strength_weak": "Слабый",
    "strength_medium": "Средний",
    "strength_medium_plus": "Средний+",
    "strength_strong": "Надёжный",
    
    # Settings window
    "settings_search": "🔍 Поиск настроек...",
    "settings_title": "⚙️ Настройки",
    "settings_subtitle": "⚙️ Настройте приложение под свои потребности",
    "settings_lang": "🌐 Язык интерфейса",
    "settings_lang_desc": "🌐 Выберите язык интерфейса",
    "settings_sound": "🔊 Звук приложения",
    "settings_theme": "🎨 Тема оформления",
    "settings_theme_desc": "🎨 Выберите оформление приложения",
    "settings_radius": "🔘 Закругление углов",
    "radius_desc": "🔘 Скругление углов элементов",
    "font_size": "🔤 Размер шрифта",
    "font_size_desc": "🔤 Размер текста в интерфейсе",
    "theme_sys": "💻 Системная",
    "theme_dark": "🌙 Тёмная",
    "theme_light": "☀️ Светлая",
    "sound_on": "🔊 Звук: вкл",
    "sound_off": "🔇 Звук: выкл",
    "sound_desc": "🔊 Звуковые эффекты при действиях",
    "close": "❌ Закрыть",
    "ok": "✅ OK",
    "cancel": "❌ Отмена",
    "yes": "✅ Да",
    "no": "❌ Нет",
    "save": "💾 Сохранить",
    "delete": "🗑️ Удалить",
    "edit": "✏️ Редактировать",
    "copy": "📋 Копировать",
    "clear": "🗑️ Очистить",
    "back": "🔙 Назад",
    "next": "➡️ Далее",
    "finish": "✅ Завершить",
    "apply": "✅ Применить",
    "reset": "🔄 Сбросить",
    "refresh": "🔄 Обновить",
    "tab_design": "🎨 Дизайн",
    "tab_security": "🔒 Безопасность",
    "tab_general": "⚙️ Общие",
    "tab_cloud": "☁ Облако",
    
    # RGB Settings
    "rgb_label": "🌈 RGB-подсветка",
    "rgb_label_desc": "🌈 Цветная анимация границ",
    "rgb_on": "✅ Вкл",
    "rgb_off": "❌ Выкл",
    "rgb_speed": "⚡ Скорость RGB",
    "rgb_speed_desc": "⚡ Скорость анимации",
    "rgb_speed_slow": "🐢 Медленная",
    "rgb_speed_normal": "⚡ Нормальная",
    "rgb_speed_fast": "🚀 Быстрая",
    "rgb_width": "📏 Толщина RGB",
    "rgb_width_desc": "📏 Толщина подсветки",
    "rgb_width_thin": "➖ Тонкая",
    "rgb_width_normal": "➖➖ Средняя",
    "rgb_width_thick": "🔲 Толстая",
    
    # Auto save
    "auto_save": "💾 Автосохранение",
    "auto_save_desc": "💾 Автоматическое сохранение паролей",
    "auto_save_on": "✅ Включено",
    "auto_save_off": "❌ Выключено",
    "auto_save_enabled": "✅ Автосохранение включено",
    "auto_save_disabled": "❌ Автосохранение выключено",
    "auto_save_label": "💾 Автосохранение",
    
    # Auto lock
    "auto_lock": "🔒 Автоблокировка",
    "auto_lock_desc": "🔒 Автоматическая блокировка при бездействии",
    "auto_lock_timeout": "⏰ Таймаут блокировки: {0} мин",
    "auto_lock_title": "🔒 Программа заблокирована",
    "unlock": "🔓 Разблокировать",
    
    # Clipboard
    "clip_timeout": "📋 Очистка буфера: {0} сек",
    "clip_timeout_desc": "📋 Автоочистка буфера обмена",
    "clipboard_cleared": "✅ Буфер обмена очищен",
    "clipboard_auto_clear": "📋 Автоочистка буфера через {0} сек",
    "clear_clipboard": "🗑️ Очистить буфер обмена",
    "pwd_done": "✅ Пароль скопирован",
    "copied": "✅ Скопировано! ({0}с)",
    
    # Master password
    "master_title": "🔐 Мастер-пароль",
    "master_desc": "🔐 Защита доступа к программе",
    "master_prompt": "🔑 Введите мастер-пароль:",
    "master_set_title": "🔐 Установить мастер-пароль",
    "master_set_prompt": "🔑 Придумайте мастер-пароль:",
    "master_confirm": "✅ Подтвердите мастер-пароль:",
    "master_mismatch": "❌ Пароли не совпадают",
    "master_wrong": "❌ Неверный пароль! Попытка {0} из {1}",
    "master_blocked": "🚫 Превышено число попыток. Программа закрыта",
    "master_set_ok": "✅ Мастер-пароль установлен",
    "master_removed": "✅ Мастер-пароль удалён",
    "master_btn_set": "🔐 Установить мастер-пароль",
    "master_btn_remove": "🗑️ Удалить мастер-пароль",
    "master_current": "📊 Статус:",
    "master_status_set": "✅ Установлен",
    "master_status_not_set": "❌ Не установлен",
    "master_remove_confirm": "⚠️ Удалить мастер-пароль?",
    "master_remove_prompt": "🔑 Введите текущий мастер-пароль:",
    "master_not_set": "❌ Мастер-пароль не установлен",
    "master_already_set": "✅ Мастер-пароль уже установлен",
    "master_set_error": "❌ Ошибка установки мастер-пароля",
    "master_remove_error": "❌ Ошибка удаления мастер-пароля",
    "master_status_text": "🔐 Мастер-пароль: установлен",
    "master_status_not_set_text": "⚠️ Мастер-пароль: не установлен",
    "master_too_short": "⚠️ Пароль слишком короткий. Минимум 8 символов",
    "master_weak": "⚠️ Пароль слишком простой. Добавьте цифру или спецсимвол",
    "master_verified": "✅ Мастер-пароль подтверждён",
    
    # Database window
    "db_title": "🗄️ База паролей",
    "db_search": "🔍 Поиск",
    "db_search_placeholder": "🔍 Поиск по метке, паролю, URL, логину, email...",
    "db_save_current": "💾 Сохранить текущий пароль",
    "db_save_current_btn": "💾 Сохранить текущий пароль",
    "db_saved": "✅ Пароль сохранён!",
    "db_save_success": "✅ Пароль сохранён!",
    "db_no_pass": "❌ Сначала сгенерируйте пароль!",
    "db_count": "📊 Записей: {0}",
    "db_empty": "📭 База пуста",
    "db_no_label": "🏷️ Без метки",
    "db_edit_title": "✏️ Редактировать запись",
    "db_edit_label": "📝 Метка",
    "db_edit_pass": "🔑 Пароль",
    "db_edit_url": "🔗 URL / Сайт",
    "db_edit_username": "👤 Логин",
    "db_edit_email": "📧 Email",
    "db_edit_category": "📁 Категория",
    "db_edit_favorite": "⭐ Избранное",
    "db_category_filter": "📁 Категория",
    "db_favorites_only": "⭐ Только избранные",
    "db_copy": "Копировать",
    "db_edit": "Изменить",
    "db_delete": "Удалить",
    "db_del_confirm": "🗑️ Удалить эту запись?",
    "db_delete_success": "✅ Запись удалена!",
    "db_import": "📂 Импорт паролей",
    "db_label_prompt": "🏷️ Метка:",
    "db_save_error": "❌ Ошибка сохранения",
    "db_delete_error": "❌ Ошибка удаления",
    "db_search_no_results": "🔍 Ничего не найдено",
    "db_notes": "📝 Заметки",
    
    # History
    "hist_empty": "📭 История пуста",
    
    # PDF
    "pdf_date": "Дата",
    "pdf_pass": "Пароль",
    "pdf_theme": "📄 Тема PDF",
    "pdf_theme_desc": "📄 Оформление экспорта в PDF",
    "pdf_theme_light": "☀️ Светлая",
    "pdf_theme_dark": "🌙 Тёмная",
    
    # QR
    "qr_closes_in": "⏰ Окно закроется через",
    "seconds_short": "сек",
    
    # Lock screen
    "lock_screen_title": "🔒 Введите мастер-пароль",
    "lock_wait": "⏳ Подождите",
    
    # HIBP
    "hibp_no_password": "⚠️ Сначала сгенерируйте пароль",
    "hibp_checking": "🔍 Проверка...",
    "hibp_safe": "✅ Пароль безопасен",
    "hibp_found": "❌ Пароль найден в {count} утечках",
    "hibp_error": "⚠️ Ошибка проверки",
    "hibp_error_title": "❌ Ошибка проверки",
    "hibp_safe_title": "✅ Пароль безопасен",
    "hibp_found_title": "🚨 ВНИМАНИЕ! Пароль скомпрометирован",
    "hibp_warning": "⚠️ Рекомендуется сменить пароль",
    "hibp_rate_limit": "⏳ Пожалуйста, подождите {0} секунд перед следующей проверкой.\nЭто защищает сервер от перегрузки.",
    "hibp_check_error": "❌ Не удалось подключиться к серверу.\nПожалуйста, проверьте интернет-соединение.",
    "hibp_safe_message": "🔒 Пароль не найден в базах утечек.\n\nБезопасно использовать.",
    "hibp_found_message": "⚠️ Пароль найден {0} раз(а) в утечках!\n\nСгенерируйте новый пароль.",
    "hibp_change_password": "🔑 Рекомендуется немедленно сменить пароль!",
    "hibp_generate_new": "🔄 Сгенерировать новый пароль",
    "hibp_close": "❌ Закрыть",
    "hibp_checking_title": "🔍 Проверка пароля...",
    "hibp_result_title": "🔍 Результат проверки утечек",
    "hibp_check_button": "🔍 Проверить утечки",
    "hibp_checking_status": "🔍 Проверка...",
    
    # Update
    "update_check": "🔄 Проверка обновлений",
    "update_available": "📦 Доступна версия {0}",
    "update_not_available": "✅ Установлена последняя версия",
    "update_available_title": "📦 Доступно обновление",
    "update_confirm_title": "🔄 Обновление",
    "update_confirm_message": "📥 Установить обновление?",
    "update_error": "❌ Ошибка обновления",
    "update_signature_error": "❌ Проверка подписи обновления не удалась!",
    "update_integrity_error": "❌ Проверка целостности обновления не удалась!",
    "update_restart": "✅ Обновление успешно загружено!\n\n🔄 Приложение перезапустится для применения изменений.",
    "download_start": "📥 Загрузка обновления...",
    "update_installing": "⚙️ Установка обновления...",
    "update_rollback": "⏪ Откат выполнен",
    "update_rollback_message": "⚠️ Установка не удалась, выполнен откат к предыдущей версии.",
    "update_cancelled": "❌ Обновление отменено",
    "update_no_backup": "📭 Нет сохранённых резервных копий для отката.",
    "update_rollback_confirm": "⚠️ Вы уверены, что хотите откатиться к предыдущей версии?\n\nЛюбые несохранённые изменения будут потеряны.",
    "update_rollback_success": "✅ Откат выполнен успешно.\n\n🔄 Приложение будет перезапущено.",
    "update_rollback_error": "❌ Не удалось выполнить откат.",
    "update_info": "ℹ️ Текущая версия: {0}",
    "update_date": "📅 Дата",
    "update_size": "📦 Размер",
    
    # Security
    "security": "🔒 Безопасность",
    "security_audit_pass": "✅ Проверка безопасности пройдена",
    "security_audit_fail": "⚠️ Обнаружены проблемы безопасности",
    "wiki_link": "📖 Wiki / Вики",
    "rate_limit_warning": "⚠️ Режим 'без повторов' снижает стойкость",
    "duplicate_warning": "⚠️ Такой пароль уже существует в базе.\n\n💾 Сохранить всё равно?",
    "skip_duplicates": "⏭️ Пропускать дубликаты паролей",
    "continue_anyway": "⚠️ Всё равно продолжить?",
    "truncate_question": "✂️ Обрезать до {0} символов?",
    
    # SQLCipher
    "sqlcipher_enabled": "✅ SQLCipher включён",
    "sqlcipher_disabled": "❌ SQLCipher отключён",
    
    # Errors
    "err_cat": "⚠️ Выберите хотя бы одну категорию",
    "err_pool_small": "⚠️ Слишком мало доступных символов",
    "err_save": "❌ Ошибка сохранения: {0}",
    "err_open": "❌ Не удалось прочитать файл: {0}",
    "err_unsupported": "❌ Неподдерживаемый тип файла: {0}",
    "err_integrity": "🚨 Критическая ошибка: Файл повреждён",
    "err_no_repeat": "⚠️ Не удалось создать пароль без повторов",
    "err_no_repeat_fallback": "\n⚠️ Использован пароль с повторами",
    "err_title": "❌ Ошибка",
    "err_encrypt": "🔒 Ошибка шифрования",
    "err_decrypt": "🔓 Ошибка дешифрования",
    "err_database": "🗄️ Ошибка базы данных",
    "err_network": "🌐 Ошибка сети",
    "err_permission": "🔐 Ошибка доступа",
    "err_copy": "📋 Ошибка копирования",
    "err_qr": "📱 Ошибка создания QR-кода",
    "err_timeout": "⏰ Превышено время ожидания",
    "err_import": "❌ Ошибка импорта модуля",
    "err_file_too_large": "📁 Файл слишком большой",
    "err_invalid_format": "📄 Неверный формат файла",
    "err_malformed": "💥 Файл повреждён",
    "err_encoding": "🔤 Неподдерживаемая кодировка файла",
    "err_file_empty": "📭 Файл пуст",
    "err_pdf_module": "📄 PDF экспорт требует модуль fpdf2\n📦 Установите: pip install fpdf2",
    "err_file_not_created": "❌ Файл не был создан!",
    
    # Integrity
    "integrity_warn": "⚠️ Файл мог быть изменён. Продолжить?",
    "integrity_fail": "🚨 Файл повреждён! Открытие отменено",
    "integrity_ok": "✅ Целостность файла подтверждена",
    
    # About
    "about_text": "🔐 Профессиональный генератор паролей\nс открытым исходным кодом",
    "about_text_simple": "🔐 Профессиональный генератор паролей\n\n© Максим Мельников\n📜 MIT License",
    
    # Status
    "status_ok": "✅ Готово",
    "status_error": "❌ Ошибка",
    "status_warning": "⚠️ Предупреждение",
    "please_wait": "⏳ Пожалуйста, подождите...",
    
    # Diceware
    "diceware": "🎲 Diceware режим",
    "diceware_word_count": "📊 Количество слов",
    "diceware_separator": "🔗 Разделитель",
    "diceware_words": "📝 Слова",
    
    # Password strength levels
    "password_strength_low": "🔴 Слабый пароль",
    "password_strength_medium": "🟡 Средний пароль",
    "password_strength_high": "🟢 Надёжный пароль",
    
    # Settings additional
    "settings_autosave": "💾 Автосохранение",
    "settings_rgb": "🌈 RGB анимация",
    "settings_sound_effect": "🔊 Звуковые эффекты",
    "settings_auto_lock": "🔒 Автоблокировка",
    "settings_corner_radius": "🔘 Закругление углов",
    "settings_font_size": "🔤 Размер шрифта",
    "settings_clipboard_timeout": "📋 Таймаут буфера",
    
    # Settings profiles
    "settings_profiles": "💾 Профили настроек",
    "settings_profiles_desc": "💾 Сохраняйте и загружайте профили настроек",
    "save_profile": "💾 Сохранить профиль",
    "load_profile": "📂 Загрузить профиль",
    "reset_profile": "🔄 Сбросить",
    "profile_saved": "✅ Профиль настроек успешно сохранён!",
    "profile_loaded": "✅ Профиль настроек успешно загружен!",
    "profile_reset": "🔄 Настройки сброшены к значениям по умолчанию!",
    "reset_profile_confirm": "⚠️ Сбросить все настройки к значениям по умолчанию?",
    
    # Export/Save
    "export_title": "💾 Сохранение",
    "export_text": "📄 Текстовые файлы",
    "export_password": "🔑 Файлы паролей",
    "export_log": "📋 Файлы логов",
    "export_pdf": "📑 PDF файлы",
    "export_all": "📁 Все файлы",
    "file_saved": "✅ Файл сохранён: {0}",
    
    # Import
    "import_title": "📂 Импорт паролей",
    "import_format": "📁 Формат импорта:",
    "import_warning": "⚠️ Импортируйте только из доверенных источников",
    "import_found": "🔍 Найдено паролей",
    "import_confirm": "📥 Импортировать?",
    "import_success": "✅ Импортировано: {0}",
    "import_error": "❌ Ошибка импорта: {0}",
    "import_no_passwords": "📭 Не найдено паролей в файле",
    "import_all_files": "📁 Все поддерживаемые файлы",
    "import_csv": "📄 CSV файлы",
    "import_json": "📄 JSON файлы",
    "import_xml": "📄 KeePass XML файлы",
    "import_1pux": "🔐 1Password 1PUX файлы",
    "import_all": "📁 Все файлы",
    "imported": "📥 Импортировано",
    "import_processing": "⏳ Обработка файла...",
    "import_progress": "⏳ Импорт...",
    "import_result": "📥 Импортировано: {0}\n⏭️ Пропущено: {1}",
    
    # 2FA
    "2fa_title": "🔐 Двухфакторная аутентификация",
    "2fa_settings_title": "⚙️ Настройки 2FA",
    "2fa_setup_title": "🔧 Настройка 2FA",
    "2fa_verify_title": "✅ Подтверждение 2FA",
    "2fa_verify_disable": "🔑 Введите код 2FA для подтверждения отключения:",
    "2fa_verify_regenerate": "🔄 Введите код 2FA для генерации новых резервных кодов:",
    "2fa_enable": "🔒 Включить 2FA",
    "2fa_disable": "🔓 Отключить 2FA",
    "2fa_status_enabled": "✅ Включена",
    "2fa_status_disabled": "❌ Отключена",
    "2fa_description": "🔐 Двухфакторная аутентификация добавляет дополнительный уровень безопасности.\n\nПри каждом входе потребуется вводить 6-значный код из приложения-аутентификатора.",
    "2fa_scan_qr": "📱 Отсканируйте этот QR-код приложением-аутентификатором:",
    "2fa_or_enter_manually": "✏️ Или введите этот код вручную:",
    "2fa_enter_code": "🔢 Введите код подтверждения:",
    "2fa_enter_verification": "🔢 Введите код из приложения-аутентификатора:",
    "2fa_enter_backup": "🎫 Введите резервный код (формат: XXXXXXXX):",
    "2fa_invalid_code": "❌ Неверный код подтверждения",
    "2fa_incorrect": "❌ Неверный код. Попробуйте ещё раз",
    "2fa_enabled_success": "✅ Двухфакторная аутентификация успешно включена!\n\n💾 Сохраните резервные коды в надёжном месте",
    "2fa_disabled_success": "✅ Двухфакторная аутентификация отключена",
    "2fa_disable_confirm": "🔐 2FA уже включена.\n\n❓ Вы хотите отключить её?",
    "2fa_disable_warning": "⚠️ ВНИМАНИЕ: Отключение 2FA сделает ваш аккаунт менее защищённым!\n\n❓ Вы уверены, что хотите отключить 2FA?",
    "2fa_master_required": "🔐 Сначала установите мастер-пароль перед включением 2FA",
    "2fa_setup_cancelled": "❌ Настройка 2FA отменена",
    "2fa_backup_codes": "📋 Резервные коды",
    "2fa_backup_codes_info": "🎫 Резервные коды",
    "2fa_backup_title": "🎫 Резервный код",
    "2fa_backup_warning": "⚠️ Сохраните резервные коды! Они необходимы для восстановления доступа",
    "2fa_backup_warning_detailed": "⚠️ Сохраните эти коды в надёжном месте!\n🔑 Каждый код можно использовать только один раз",
    "2fa_backup_count": "📊 Осталось резервных кодов: {0}",
    "2fa_backup_used": "⚠️ Использован резервный код!\n🔄 Сгенерируйте новые резервные коды в настройках",
    "2fa_invalid_try_backup": "❌ Неверный код.\n\n🎫 Использовать резервный код?",
    "2fa_invalid_backup": "❌ Неверный резервный код",
    "2fa_regenerate_backup": "🔄 Сгенерировать новые резервные коды",
    "2fa_backup_regenerated": "✅ Новые резервные коды успешно сгенерированы",
    "2fa_regenerate_backup_confirm": "🔄 Генерация новых резервных кодов сделает старые недействительными.\n\n❓ Продолжить?",
    "2fa_error": "❌ Ошибка верификации 2FA",
    "2fa_missing_secret": "🔐 Секрет 2FA отсутствует",
    "2fa_cancelled": "❌ Верификация 2FA отменена",
    "2fa_module_error": "📦 Модуль 2FA недоступен",
    
    # QR module
    "qr_module_missing": "📱 Модуль qrcode не установлен.\n📦 Установите: pip install qrcode[pil]",
    
    # Copy all
    "copy_all": "📋 Копировать все",
    
    # Settings search placeholder
    "settings_search_placeholder": "🔍 Поиск настроек...",
    
    # Open title
    "open_title": "📂 Выберите файл пароля",
    
    # ========== NEW KEYS FOR MULTILANGUAGE FILE SAVING ==========
    "export_date": "📅 Дата",
    "export_password_label": "🔑 Пароль",
    
    # ========== NEW KEYS FOR PASSPHRASE GENERATOR ==========
    "passphrase_title": "🔐 Генератор парольных фраз (Diceware)",
    "passphrase_desc": "Генерируйте безопасные парольные фразы методом Diceware.\nКаждое слово добавляет ~13 бит энтропии.\nФраза из 6 слов даёт ~78 бит энтропии.",
    "passphrase_settings": "⚙️ Настройки",
    "passphrase_word_count": "📊 Количество слов",
    "passphrase_separator": "🔗 Разделитель",
    "passphrase_capitalize": "🔠 Заглавные буквы",
    "passphrase_add_number": "🔢 Добавить число",
    "passphrase_number_position": "📍 Позиция числа",
    "passphrase_position_start": "🏁 Начало",
    "passphrase_position_end": "🏁 Конец",
    "passphrase_position_random": "🎲 Случайно",
    "passphrase_generate": "🎲 Сгенерировать",
    "passphrase_copy_all": "📋 Копировать всё",
    "passphrase_clear": "🗑️ Очистить",
    "passphrase_entropy": "🔢 Энтропия",
    "passphrase_generate_count": "🔢 Количество фраз",
    "passphrase_nothing_to_copy": "📭 Нечего копировать. Сначала сгенерируйте фразы.",
    "passphrase_copied_title": "✅ Скопировано",
    "passphrase_copied": "✅ Парольные фразы скопированы в буфер обмена!",
    "passphrase_error": "❌ Ошибка генерации парольной фразы",

    # ========== v3 NEW FEATURES ==========
    "db_sort": "↕ Сортировка",
    "db_sort_favorite": "⭐ Сначала избранные",
    "db_sort_date_desc": "📅 Сначала новые",
    "db_sort_date_asc": "📅 Сначала старые",
    "db_sort_label_asc": "🔤 Имя А-Я",
    "db_sort_label_desc": "🔤 Имя Я-А",
    "db_sort_category": "🗂 По категориям",
    "export_url": "🌐 URL",
    "export_username": "👤 Логин",
    "export_email": "📧 Email",
    "export_category": "🗂 Категория",
    "export_kdbx": "🔐 KeePass (.kdbx)",
    "sync_title": "☁ Облачная синхронизация",
    "sync_provider": "🌐 Провайдер",
    "sync_url": "🔗 URL сервера WebDAV",
    "sync_username": "👤 Логин",
    "sync_password": "🔑 Пароль",
    "sync_upload": "☁ Загрузить на сервер",
    "sync_download": "⬇ Скачать с сервера",
    "sync_test": "🔌 Проверить соединение",
    "sync_strategy": "⚡ Стратегия",
    "sync_strat_upload": "☁ Всегда загружать",
    "sync_strat_download": "⬇ Всегда скачивать",
    "sync_strat_newest": "🕐 Использовать новейший",
    "sync_conn_ok": "✅ Соединение успешно",
    "sync_conn_fail": "❌ Соединение не удалось",
    "sync_success_up": "✅ База данных загружена на сервер",
    "sync_success_down": "✅ База данных скачана с сервера",
    "sync_error": "❌ Ошибка синхронизации",
    "sync_no_lib": "⚠ Установите requests: pip install requests",
    "autotype_title": "⌨ Автовставка пароля",
    "autotype_btn": "⌨ Вставить пароль",
    "autotype_ok": "✅ Пароль вставлен",
    "autotype_fail": "❌ Ошибка автовставки",
    "autotype_clip": "📋 Копировать + Ctrl+V",
    "autotype_no_support": "⚠ Автовставка недоступна на этой системе",
    "vm_dev_mode": "🛠 DEV-режим: обнаружение VM отключено",

    # copy URL/username buttons
    "db_copy_url": "🌐 Копировать URL",
    "db_copy_username": "👤 Копировать логин",
    "db_no_url": "URL не задан",
    "db_no_username": "Логин не задан",

    # cloud sync tab
    "tab_cloud": "☁ Облако",
    "sync_desc": "Синхронизируйте зашифрованную базу данных через WebDAV. Ключ никогда не покидает устройство.",
    "sync_security_note": "🔒 Синхронизируется только зашифрованный файл — ключ остаётся на устройстве",

    # --- additional v3 keys ---
    "db_edit_notes": "📝 Заметки",
    "db_edit_password": "🔑 Пароль",
    "export_no_data": "Нет данных для экспорта",
    "sync_save": "💾 Сохранить настройки",
    "sync_dialog_title": "☁ Настройки синхронизации",
    "sync_provider_header": "☁  Провайдер",
    "sync_provider_webdav": "🔗 Свой WebDAV",
    "sync_testing": "⏳ Проверка соединения...",
    "sync_uploading": "⏳ Загрузка в облако...",
    "sync_downloading": "⏳ Скачивание из облака...",
    "sync_not_configured": "❌ Не настроено",
    "sync_nextcloud_desc": "Ваш собственный Nextcloud сервер",
    "sync_pcloud_desc": "Швейцарское облачное хранилище",
    "sync_box_desc": "Облачное хранилище Box",
    "sync_webdav_desc": "Любой WebDAV-совместимый сервер",
    "sync_placeholder_user": "ваш_логин",
    "select_all": "Все",
    "select_none": "Снять",
    "export_fields_btn": "Выбрать поля",
    "export_encoding_short": "Кодировка:",
    "sync_hint": "ℹ Зашифрованная база данных безопасна для любого облака",

    # --- New features ---
    "trash_btn": "🗑 Корзина",
    "trash_title": "🗑 Корзина",
    "trash_empty": "🗑 Очистить корзину",
    "trash_empty_confirm": "Удалить ВСЕ элементы корзины навсегда?",
    "trash_empty_label": "Корзина пуста",
    "trash_deleted": "Удалено",
    "trash_restore": "↩ Восстановить",
    "trash_del_perm": "✕ Удалить навсегда",
    "trash_perm_del": "Удалить навсегда?",
    "trash_items": "элементов",
    "trash_confirm": "В корзину?",
    "stats_btn": "📊 Статистика",
    "stats_title": "📊 Статистика хранилища",
    "stats_total": "Всего записей",
    "stats_weak": "Слабые пароли",
    "stats_dupl": "Дублей паролей",
    "stats_no_url": "Без URL",
    "stats_old_pwd": "Пароль старше 90 дней",
    "stats_in_trash": "В корзине",
    "stats_with_tags": "Записей с тегами",
    "stats_health": "Здоровье хранилища:",
    "bulk_btn": "☰  Действия со всеми  ▾",
    "bulk_select_all": "☑  Выбрать все",
    "bulk_delete_all": "🗑  Удалить все",
    "bulk_move_all": "📁  Переместить все",
    "bulk_export_all": "📤  Экспорт всех",
    "bulk_del_all_confirm": "Удалить ВСЕ записи? Это нельзя отменить!",
    "bulk_move_title": "Переместить все в категорию",
    "bulk_move_label": "Категория для ВСЕХ записей:",
    "bulk_move_ph": "Введите или выберите",
    "bulk_select_info": "Все записи выбраны для действия.",
    "cf_title": "Доп. поля",
    "cf_name": "Название поля",
    "cf_val": "Значение",
    "cf_hide": "Скрыть",
    "cf_add": "+ Добавить поле",
    "tags_title": "Теги",
    "tags_hint": "Через запятую",
    "age_changed": "Пароль изменён",
    "db_duplicate": "⧉ Дублировать",
    "duplicate_prefix": "Копия",
    "qs_title": "Быстрый поиск",
    "qs_placeholder": "Введите запрос...",
    "db_trash_confirm": "В корзину?",
    "age_warn": "⚠ {d} дн.",
    "age_danger": "🔴 {d} дн.",
    "icon_eye_off": "🙈",
    "icon_eye": "👁",
    "icon_copy": "⧉",
    "icon_sync": "☁",
    "icon_stats": "📊",
    "icon_trash": "🗑",
    "icon_calendar": "📅",
    "icon_key": "🔑",
    "icon_success_sym": "✓",
    "icon_warning_sym": "⚠",
    "icon_question_sym": "?",
    "icon_info_sym": "ℹ",
    "icon_err": "✗",
    "icon_ok": "✓",
    "icon_danger": "🔴",
    "icon_warn": "⚠",
    "icon_search": "🔍",
    "icon_tag": "🏷",
    "icon_field": "🔧",
    "icon_date": "📅",
    "rating_stars": "★★★★★",
    "icon_close_sm": "✕",
    "icon_star_empty": "☆",
    "icon_star": "★",
    "icon_passphrase": "🔐",
    "copied_ok": "Скопировано!",
}

# ==================== EXPORTS ====================

__all__: List[str] = [
    'RUSSIAN_DICT',
]