"""
Language dictionaries (RU, EN, UA)
"""
from typing import Dict

LANGUAGES: Dict[str, Dict[str, str]] = {
    "RU": {
        "win_title": "Secure Pass Pro v4.0",
        "menu_title": "Меню",
        "len": "Длина",
        "author": "Автор: Максим Мельников",
        "upper": "Заглавные буквы",
        "lower": "Строчные буквы",
        "digits": "Цифры",
        "symb": "Спецсимволы",
        "ambig": "Исключить похожие (i, l, 1...)",
        "unambig": "Исключить не однозначные",
        "at_least": "Минимум 1 из каждой категории",
        "hide": "Скрывать символы",
        "no_repeat": "Избегать повторов символов подряд",
        "btn_gen": "Сгенерировать",
        "btn_copy": "Копировать пароль",
        "btn_save": "Сохранить в файл",
        "btn_open": "Открыть файл",
        "btn_qr": "QR-код пароль",
        "btn_hist": "История",
        "btn_db": "База паролей",
        "btn_upd": "Обновить программу",
        "btn_about": "О программе",
        "btn_settings": "Настройки",
        "settings_title": "Настройки",
        "settings_lang": "Язык интерфейса",
        "settings_sound": "Звук приложения",
        "settings_theme": "Тема оформления",
        "settings_radius": "Закругление углов",
        "theme_sys": "Системная",
        "theme_dark": "Тёмная",
        "theme_light": "Светлая",
        "sound_on": "Звук: вкл",
        "sound_off": "Звук: выкл",
        "close": "Закрыть",
        "ok": "Ok",
        "cancel": "Отмена",
        "yes": "Да",
        "no": "Нет",
        "copied": "Скопировано! ({0}с)",
        "strength": "Стойкость: ~{0} вариантов",
        "crack_time": "{0}",
        "time_sec": "Несколько секунд на взлом",
        "time_day": "Дни на взлом",
        "time_year": "Года на взлом",
        "time_cent": "Столетия на взлом",
        "st_low": "Слабый пароль",
        "st_mid": "Средний пароль",
        "st_high": "Надёжный пароль",
        "tt_gen": "Создать новый случайный пароль",
        "tt_copy": "Копировать в буфер (очистка через {0} сек)",
        "tt_save": "Сохранить текущий пароль в файл",
        "tt_open": "Открыть пароль из файла",
        "tt_qr": "Создать QR-код для быстрого сканирования",
        "tt_hist": "Показать последние 50 паролей",
        "tt_db": "Открыть хранилище паролей (SQLite)",
        "tt_upd": "Проверить наличие новой версии на GitHub",
        "tt_about": "Информация о разработчике и программе",
        "tt_settings": "Язык, звук и тема оформления",
        "tt_eye": "Показать / скрыть пароль",
        "tt_no_repeat": "Не допускать одинаковых символов подряд",
        "tt_auto_lock": "Автоматическая блокировка при бездействии",
        "hist_empty": "История пуста...",
        "btn_clear_hist": "Очистить историю",
        "db_title": "База паролей",
        "db_label_prompt": "Метка:",
        "db_saved": "Пароль сохранён в базу!",
        "db_empty": "База пуста...",
        "db_copy": "Копировать",
        "db_delete": "Удалить",
        "db_edit": "Изменить",
        "db_save_current": "Сохранить текущий пароль",
        "db_no_pass": "Сначала сгенерируйте пароль!",
        "db_count": "Записей: {0}",
        "db_search": "Поиск...",
        "db_del_confirm": "Удалить эту запись?",
        "db_edit_title": "Редактировать запись",
        "db_edit_label": "Метка:",
        "db_edit_pass": "Пароль:",
        "pdf_date": "Дата",
        "pdf_pass": "Пароль",
        "master_title": "Мастер-пароль",
        "master_prompt": "Введите мастер-пароль для доступа к программе:",
        "master_set_title": "Установить мастер-пароль",
        "master_set_prompt": "Придумайте мастер-пароль:",
        "master_confirm": "Подтвердите мастер-пароль:",
        "master_mismatch": "Пароли не совпадают!",
        "master_wrong": "Неверный мастер-пароль! Попытка {0} из {1}.",
        "master_blocked": "Превышено число попыток. Программа закрыта.",
        "master_set_ok": "Мастер-пароль установлен.",
        "master_removed": "Мастер-пароль удалён.",
        "master_btn_set": "Установить мастер-пароль",
        "master_btn_remove": "Удалить мастер-пароль",
        "master_current": "Статус:",
        "master_status_set": "Установлен",
        "master_status_not_set": "Не установлен",
        "master_remove_confirm": "Вы уверены, что хотите удалить мастер-пароль?",
        "master_status_text": "🔐 Мастер-пароль: установлен (Argon2id)",
        "master_status_not_set_text": "⚠️ Мастер-пароль: не установлен",
        "auto_save": "Автосохранение",
        "auto_save_on": "✅ Включено",
        "auto_save_off": "❌ Выключено",
        "auto_save_enabled": "✅ Автосохранение включено!\nПароли будут сохраняться автоматически.",
        "auto_save_disabled": "❌ Автосохранение выключено.",
        "auto_save_label": "📁 Автосохранение",
        "rgb_label": "🌈 RGB-подсветка",
        "rgb_on": "Вкл",
        "rgb_off": "Выкл",
        "auto_lock": "Автоблокировка",
        "auto_lock_timeout": "Таймаут блокировки: {0} мин",
        "auto_lock_title": "Программа заблокирована",
        "unlock": "Разблокировать",
        "clip_timeout": "Очистка буфера: {0} сек",
        "tt_clip_timeout": "Через сколько секунд буфер обмена будет очищен",
        "clipboard_cleared": "✅ Буфер обмена очищен!",
        "security": "Безопасность",
        "wiki_link": "Читать Security Logic Wiki",
        "err_cat": "Выберите хотя бы одну категорию!",
        "err_pool_small": "Слишком мало доступных символов!",
        "err_save": "Ошибка сохранения: {0}",
        "err_open": "Не удалось прочитать файл: {0}",
        "err_unsupported": "Неподдерживаемый тип файла: {0}",
        "err_integrity": "Критическая ошибка: Файл поврежден!",
        "err_no_repeat": "Не удалось создать пароль без повторов.",
        "err_no_repeat_fallback": "\nИспользован пароль с повторами.",
        "err_title": "Ошибка",
        "integrity_warn": "⚠ Файл мог быть изменён. Продолжить?",
        "integrity_fail": "🚨 Файл повреждён! Открытие отменено.",
        "integrity_ok": "✅ Целостность файла подтверждена.",
        "about_text": "Secure Pass Pro v4.0\n\nПрофессиональный инструмент для генерации паролей.\nИспользует криптографически стойкие алгоритмы.\n\n✅ Argon2id\n✅ SQLite хранилище"
    },
    "EN": {
        "win_title": "Secure Pass Pro v4.0",
        "menu_title": "Menu",
        "len": "Length",
        "author": "Author: Maxim Melnikov",
        "upper": "Uppercase",
        "lower": "Lowercase",
        "digits": "Digits",
        "symb": "Special symbols",
        "ambig": "Exclude ambiguous (i, l, 1...)",
        "unambig": "Exclude non-obvious",
        "at_least": "Min 1 from each category",
        "hide": "Hide symbols",
        "no_repeat": "Avoid consecutive repeated characters",
        "btn_gen": "Generate",
        "btn_copy": "Copy password",
        "btn_save": "Save to file",
        "btn_open": "Open file",
        "btn_qr": "Password QR-code",
        "btn_hist": "History",
        "btn_db": "Password vault",
        "btn_upd": "Update program",
        "btn_about": "About",
        "btn_settings": "Settings",
        "settings_title": "Settings",
        "settings_lang": "Interface language",
        "settings_sound": "App sound",
        "settings_theme": "Appearance theme",
        "settings_radius": "Corner radius",
        "theme_sys": "System",
        "theme_dark": "Dark",
        "theme_light": "Light",
        "sound_on": "Sound: on",
        "sound_off": "Sound: off",
        "close": "Close",
        "ok": "Ok",
        "cancel": "Cancel",
        "yes": "Yes",
        "no": "No",
        "copied": "Copied! ({0}s)",
        "strength": "Strength: ~{0} combos",
        "crack_time": "{0}",
        "time_sec": "A few seconds to crack",
        "time_day": "Days to crack",
        "time_year": "Years to crack",
        "time_cent": "Centuries to crack",
        "st_low": "Weak password",
        "st_mid": "Medium password",
        "st_high": "Strong password",
        "tt_gen": "Create a new random password",
        "tt_copy": "Copy to clipboard (clears in {0} sec)",
        "tt_save": "Save current password to file",
        "tt_open": "Open password from file",
        "tt_qr": "Create a QR code for quick scanning",
        "tt_hist": "Show last 50 generated passwords",
        "tt_db": "Open password vault (SQLite)",
        "tt_upd": "Check for new version on GitHub",
        "tt_about": "Developer and program info",
        "tt_settings": "Language, sound and theme",
        "tt_eye": "Show / hide password",
        "tt_no_repeat": "Prevent the same character appearing consecutively",
        "tt_auto_lock": "Auto lock on inactivity",
        "hist_empty": "History is empty...",
        "btn_clear_hist": "Clear history",
        "db_title": "Password vault",
        "db_label_prompt": "Label:",
        "db_saved": "Password saved to vault!",
        "db_empty": "Vault is empty...",
        "db_copy": "Copy",
        "db_delete": "Delete",
        "db_edit": "Edit",
        "db_save_current": "Save current password",
        "db_no_pass": "Generate a password first!",
        "db_count": "Records: {0}",
        "db_search": "Search...",
        "db_del_confirm": "Delete this record?",
        "db_edit_title": "Edit record",
        "db_edit_label": "Label:",
        "db_edit_pass": "Password:",
        "pdf_date": "Date",
        "pdf_pass": "Password",
        "master_title": "Master password",
        "master_prompt": "Enter master password to access the program:",
        "master_set_title": "Set master password",
        "master_set_prompt": "Create a master password:",
        "master_confirm": "Confirm master password:",
        "master_mismatch": "Passwords do not match!",
        "master_wrong": "Wrong master password! Attempt {0} of {1}.",
        "master_blocked": "Too many failed attempts. Program closed.",
        "master_set_ok": "Master password has been set.",
        "master_removed": "Master password removed.",
        "master_btn_set": "Set master password",
        "master_btn_remove": "Remove master password",
        "master_current": "Status:",
        "master_status_set": "Set",
        "master_status_not_set": "Not set",
        "master_remove_confirm": "Are you sure you want to remove the master password?",
        "master_status_text": "🔐 Master password: set (Argon2id)",
        "master_status_not_set_text": "⚠️ Master password: not set",
        "auto_save": "Auto save",
        "auto_save_on": "✅ On",
        "auto_save_off": "❌ Off",
        "auto_save_enabled": "✅ Auto save enabled!\nPasswords will be saved automatically.",
        "auto_save_disabled": "❌ Auto save disabled.",
        "auto_save_label": "📁 Auto save",
        "rgb_label": "🌈 RGB border",
        "rgb_on": "On",
        "rgb_off": "Off",
        "auto_lock": "Auto lock",
        "auto_lock_timeout": "Lock timeout: {0} min",
        "auto_lock_title": "Program locked",
        "unlock": "Unlock",
        "clip_timeout": "Clipboard clear: {0} sec",
        "tt_clip_timeout": "Seconds before clipboard is cleared",
        "clipboard_cleared": "✅ Clipboard cleared!",
        "security": "Security",
        "wiki_link": "Read Security Logic Wiki",
        "err_cat": "Select at least one category!",
        "err_pool_small": "Too few available characters!",
        "err_save": "Save failed: {0}",
        "err_open": "Could not read file: {0}",
        "err_unsupported": "Unsupported file type: {0}",
        "err_integrity": "Critical error: File corrupted!",
        "err_no_repeat": "Could not generate password without repeats.",
        "err_no_repeat_fallback": "\nPassword with repeats used.",
        "err_title": "Error",
        "integrity_warn": "⚠ File may have been modified. Continue?",
        "integrity_fail": "🚨 File corrupted! Opening cancelled.",
        "integrity_ok": "✅ File integrity verified.",
        "about_text": "Secure Pass Pro v4.0\n\nProfessional password generation tool.\nUses cryptographically secure algorithms.\n\n✅ Argon2id\n✅ SQLite storage"
    },
    "UA": {
        "win_title": "Secure Pass Pro v4.0",
        "menu_title": "Меню",
        "len": "Довжина",
        "author": "Автор: Максим Мельніков",
        "upper": "Великі літери",
        "lower": "Малі літери",
        "digits": "Цифри",
        "symb": "Спецсимволи",
        "ambig": "Виключити схожі (i, l, 1...)",
        "unambig": "Виключити не однозначні",
        "at_least": "Мінімум 1 з категорії",
        "hide": "Приховати символи",
        "no_repeat": "Уникати повторів символів поспіль",
        "btn_gen": "Згенерувати",
        "btn_copy": "Копіювати пароль",
        "btn_save": "Зберегти у файл",
        "btn_open": "Відкрити файл",
        "btn_qr": "QR-код пароль",
        "btn_hist": "Історія",
        "btn_db": "База паролів",
        "btn_upd": "Оновити програму",
        "btn_about": "Про програму",
        "btn_settings": "Налаштування",
        "settings_title": "Налаштування",
        "settings_lang": "Мова інтерфейсу",
        "settings_sound": "Звук програми",
        "settings_theme": "Тема оформлення",
        "settings_radius": "Закруглення кутів",
        "theme_sys": "Системна",
        "theme_dark": "Темна",
        "theme_light": "Світла",
        "sound_on": "Звук: уві",
        "sound_off": "Звук: вим",
        "close": "Закрити",
        "ok": "Ok",
        "cancel": "Відміна",
        "yes": "Так",
        "no": "Ні",
        "copied": "Скопійовано! ({0}с)",
        "strength": "Стійкість: ~{0} варіантів",
        "crack_time": "{0}",
        "time_sec": "Кілька секунд на злам",
        "time_day": "Дні на злам",
        "time_year": "Роки на злам",
        "time_cent": "Століття на злам",
        "st_low": "Слабкий пароль",
        "st_mid": "Середній пароль",
        "st_high": "Надійний пароль",
        "tt_gen": "Створити новий випадковий пароль",
        "tt_copy": "Копіювати в буфер (очищення через {0} сек)",
        "tt_save": "Зберегти поточний пароль у файл",
        "tt_open": "Відкрити пароль з файлу",
        "tt_qr": "Створити QR-код для швидкого сканування",
        "tt_hist": "Показати останні 50 паролів",
        "tt_db": "Відкрити сховище паролів (SQLite)",
        "tt_upd": "Перевірити наявність нової версії на GitHub",
        "tt_about": "Інформація про розробника та програму",
        "tt_settings": "Мова, звук та тема оформлення",
        "tt_eye": "Показати / приховати пароль",
        "tt_no_repeat": "Не допускати однакових символів підряд",
        "tt_auto_lock": "Автоматичне блокування при бездіяльності",
        "hist_empty": "Історія порожня...",
        "btn_clear_hist": "Очистити історію",
        "db_title": "База паролів",
        "db_label_prompt": "Мітка:",
        "db_saved": "Пароль збережено до бази!",
        "db_empty": "База порожня...",
        "db_copy": "Копіювати",
        "db_delete": "Видалити",
        "db_edit": "Змінити",
        "db_save_current": "Зберегти поточний пароль",
        "db_no_pass": "Спочатку згенеруйте пароль!",
        "db_count": "Записів: {0}",
        "db_search": "Пошук...",
        "db_del_confirm": "Видалити цей запис?",
        "db_edit_title": "Редагувати запис",
        "db_edit_label": "Мітка:",
        "db_edit_pass": "Пароль:",
        "pdf_date": "Дата",
        "pdf_pass": "Пароль",
        "master_title": "Майстер-пароль",
        "master_prompt": "Введіть майстер-пароль для доступу до програми:",
        "master_set_title": "Встановити майстер-пароль",
        "master_set_prompt": "Придумайте майстер-пароль:",
        "master_confirm": "Підтвердіть майстер-пароль:",
        "master_mismatch": "Паролі не збігаються!",
        "master_wrong": "Невірний майстер-пароль! Спроба {0} з {1}.",
        "master_blocked": "Перевищено кількість спроб. Програму закрито.",
        "master_set_ok": "Майстер-пароль встановлено.",
        "master_removed": "Майстер-пароль видалено.",
        "master_btn_set": "Встановити майстер-пароль",
        "master_btn_remove": "Видалити майстер-пароль",
        "master_current": "Статус:",
        "master_status_set": "Встановлено",
        "master_status_not_set": "Не встановлено",
        "master_remove_confirm": "Ви впевнені, що хочете видалити майстер-пароль?",
        "master_status_text": "🔐 Майстер-пароль: встановлено (Argon2id)",
        "master_status_not_set_text": "⚠️ Майстер-пароль: не встановлено",
        "auto_save": "Автозбереження",
        "auto_save_on": "✅ Увімкнено",
        "auto_save_off": "❌ Вимкнено",
        "auto_save_enabled": "✅ Автозбереження увімкнено!\nПаролі зберігатимуться автоматично.",
        "auto_save_disabled": "❌ Автозбереження вимкнено.",
        "auto_save_label": "📁 Автозбереження",
        "rgb_label": "🌈 RGB-підсвітка",
        "rgb_on": "Уві",
        "rgb_off": "Вим",
        "auto_lock": "Автоблокування",
        "auto_lock_timeout": "Таймаут блокування: {0} хв",
        "auto_lock_title": "Програму заблоковано",
        "unlock": "Розблокувати",
        "clip_timeout": "Очищення буфера: {0} сек",
        "tt_clip_timeout": "Через скільки секунд буфер обміну буде очищено",
        "clipboard_cleared": "✅ Буфер обміну очищено!",
        "security": "Безпека",
        "wiki_link": "Читати Security Logic Wiki",
        "err_cat": "Виберіть хоча б одну категорію!",
        "err_pool_small": "Занадто мало доступних символів!",
        "err_save": "Помилка збереження: {0}",
        "err_open": "Не вдалося прочитати файл: {0}",
        "err_unsupported": "Непідтримуваний тип файлу: {0}",
        "err_integrity": "Критична помилка: Файл пошкоджений!",
        "err_no_repeat": "Не вдалося створити пароль без повторів.",
        "err_no_repeat_fallback": "\nВикористано пароль з повторами.",
        "err_title": "Помилка",
        "integrity_warn": "⚠ Файл міг бути змінений. Продовжити?",
        "integrity_fail": "🚨 Файл пошкоджений! Відкриття скасовано.",
        "integrity_ok": "✅ Цілісність файлу підтверджена.",
        "about_text": "Secure Pass Pro v4.0\n\nПрофесійний інструмент для генерації паролів.\nВикористовує криптографічно стійкі алгоритми.\n\n✅ Argon2id\n✅ SQLite сховище"
    }
}